// ————————————————————————————————————————————————————————————————————————
// The public REST API's route manifest — the single source of truth for what
// `/v1` serves.
//
// Three things read this file:
//   · convex/apiHttp.ts     — for the "supported endpoints" hint on a 404,
//   · scripts/generate-openapi.mjs — which GENERATES public/docs/api/openapi.json
//     from it, so the published spec cannot drift from the manifest,
//   · that script's `--check --live` mode, which probes every route below
//     against a running deployment, so the manifest cannot drift from the
//     dispatcher either.
//
// Pure data on purpose: no imports, no expressions, no computed keys. The
// generator parses this literal out of the source rather than importing it
// (importing anything under convex/ drags in the generated API surface, which
// plain node cannot load), and a flat literal makes that parse exact.
// ————————————————————————————————————————————————————————————————————————

export type ApiRoute = {
  method: "GET" | "POST" | "PUT" | "DELETE"
  /** OpenAPI path template, e.g. `/v1/event/{eventRef}/sessions/{sessionId}`. */
  path: string
  operationId: string
  tag: string
  summary: string
  description: string
  /** Scope enforced when the presenting key declares a scope set. */
  scope: string | null
  /** Rate-limit category, or null when the route is not rate limited. */
  bucket: string | null
  /** Request body schema name in `components.schemas`, if any. */
  requestBody: string | null
  /** Success status → response schema name (or null for an empty body). */
  responses: Array<[number, string | null]>
  /** Extra documented failure statuses beyond the standard 401/403/404. */
  errors: Array<number>
  /** Query parameter names, resolved against `components.parameters`. */
  query: Array<string>
  /** Set for the two endpoints that deliberately need no credential. */
  open: boolean
  /** multipart/form-data or application/octet-stream bodies. */
  bodyKind: "json" | "multipart" | "binary" | "none"
}

/**
 * Value lists and metadata resources share one implementation, so they share
 * one row here and the generator expands them. `statuses` is read-only by
 * design (our pipeline is a fixed enum) but still answers writes with a
 * documented 400, which the generated spec spells out.
 */
export const SETTINGS_READ_RESOURCES = [
  "fields",
  "tags",
  "tracks",
  "rooms",
  "formats",
  "levels",
  "languages",
  "statuses",
  "session-statuses",
] as const

export const METADATA_WRITE_RESOURCES = [
  "tags",
  "tracks",
  "rooms",
  "formats",
  "levels",
  "languages",
  "statuses",
] as const

/** Human labels for the generated per-resource operation summaries. */
export const RESOURCE_LABELS: Record<string, string> = {
  fields: "custom field",
  tags: "tag",
  tracks: "track",
  rooms: "room",
  formats: "format",
  levels: "level",
  languages: "language",
  statuses: "session status",
  "session-statuses": "session status",
}

export const API_ROUTES: Array<ApiRoute> = [
  // ——— Open endpoints ———
  {
    method: "GET",
    path: "/v1/event/{eventRef}/schedule.ics",
    operationId: "getScheduleFeed",
    tag: "Calendar",
    summary: "Subscribe to the event calendar",
    description:
      "RFC 5545 calendar feed of the published programme. Deliberately open: calendar clients subscribe by URL and cannot send an auth header. Only accepted, scheduled sessions of a published agenda appear.",
    scope: null,
    bucket: null,
    requestBody: null,
    responses: [[200, null]],
    errors: [404],
    query: [],
    open: true,
    bodyKind: "none",
  },
  {
    method: "POST",
    path: "/v1/_echo",
    operationId: "echoWebhookDelivery",
    tag: "Webhooks",
    summary: "Signature-verifying echo sink",
    description:
      "Test target for webhook deliveries. Pass the endpoint's signing secret as `?secret=` and the sink recomputes the HMAC over the exact body: it answers 200 only when the signature verifies, and 401 otherwise. Point a webhook here to prove end-to-end delivery and signing without standing up a server.",
    scope: null,
    bucket: null,
    requestBody: null,
    responses: [[200, "EchoResult"]],
    errors: [401],
    query: ["secret"],
    open: true,
    bodyKind: "json",
  },

  // ——— Events ———
  {
    method: "GET",
    path: "/v1/events",
    operationId: "listEvents",
    tag: "Events",
    summary: "List events",
    description:
      "Every event in every workspace the credential belongs to, newest first. The read-only demo token sees all demo events.",
    scope: "read:events",
    bucket: null,
    requestBody: null,
    responses: [[200, "EventsPage"]],
    errors: [],
    query: ["page", "pageSize"],
    open: false,
    bodyKind: "none",
  },

  // ——— Sessions: read ———
  {
    method: "GET",
    path: "/v1/event/{eventRef}/sessions",
    operationId: "listSessions",
    tag: "Sessions",
    summary: "List sessions",
    description:
      "Paginated sessions. With no filters this returns the accepted programme — the behaviour this endpoint has always had — so existing consumers are unaffected. Passing any filter (`status`, `is_abstract`, `track_id`, `tag_id`, `search`) opts into the full pipeline, soft-deleted rows excluded.",
    scope: "read:sessions",
    bucket: null,
    requestBody: null,
    responses: [[200, "SessionsPage"]],
    errors: [],
    query: [
      "page",
      "pageSize",
      "status",
      "is_abstract",
      "track_id",
      "tag_id",
      "search",
      "expand",
      "include_deleted",
    ],
    open: false,
    bodyKind: "none",
  },
  {
    method: "POST",
    path: "/v1/event/{eventRef}/sessions",
    operationId: "searchSessions",
    tag: "Sessions",
    summary: "Search sessions",
    description:
      "Filter, sort and page through sessions and abstracts. Results carry the full session shape including `custom_fields`, `participants` and nested track/room metadata.",
    scope: "read:sessions",
    bucket: null,
    requestBody: "SessionSearchBody",
    responses: [[200, "SessionsPage"]],
    errors: [400],
    query: ["page", "pageSize"],
    open: false,
    bodyKind: "json",
  },
  {
    method: "POST",
    path: "/v1/event/{eventRef}/sessions/status",
    operationId: "searchSessionStatuses",
    tag: "Sessions",
    summary: "Search sessions by status",
    description:
      "Lightweight id + status projection with no joins — the cheap way to reconcile a mirror. Soft-deleted rows are included, carrying `deleted_at`.",
    scope: "read:sessions",
    bucket: null,
    requestBody: "SessionSearchBody",
    responses: [[200, "SessionStatusesPage"]],
    errors: [400],
    query: ["page", "pageSize"],
    open: false,
    bodyKind: "json",
  },
  {
    method: "GET",
    path: "/v1/event/{eventRef}/sessions/{sessionId}",
    operationId: "getSession",
    tag: "Sessions",
    summary: "Get a session",
    description:
      "One session in full. Soft-deleted sessions read as 404 unless `expand=deleted` is passed. `expand=files` inlines the session's attachments.",
    scope: "read:sessions",
    bucket: "entity_reads",
    requestBody: null,
    responses: [[200, "SessionEnvelope"]],
    errors: [429],
    query: ["expand"],
    open: false,
    bodyKind: "none",
  },

  // ——— Sessions: write ———
  {
    method: "POST",
    path: "/v1/event/{eventRef}/sessions/create",
    operationId: "createSession",
    tag: "Session Writes",
    summary: "Create a session",
    description:
      "Creates a programme session, or an abstract when `is_abstract` is true. A submitter is resolved from `submitter_email` (created if new) and attached as the first speaker, so a session is never speakerless.",
    scope: "write:sessions",
    bucket: "session_writes",
    requestBody: "SessionWriteBody",
    responses: [[201, "SessionEnvelope"]],
    errors: [400, 429],
    query: [],
    open: false,
    bodyKind: "json",
  },
  {
    method: "PUT",
    path: "/v1/event/{eventRef}/sessions/{sessionId}",
    operationId: "updateSession",
    tag: "Session Writes",
    summary: "Update a session",
    description:
      "Partial update. Send the `updated_at` you last read for optimistic concurrency — a mismatch answers 409 with the current value rather than silently clobbering someone else's edit.",
    scope: "write:sessions",
    bucket: "session_writes",
    requestBody: "SessionWriteBody",
    responses: [[200, "SessionEnvelope"]],
    errors: [400, 409, 429],
    query: [],
    open: false,
    bodyKind: "json",
  },
  {
    method: "DELETE",
    path: "/v1/event/{eventRef}/sessions/{sessionId}",
    operationId: "deleteSession",
    tag: "Session Writes",
    summary: "Soft-delete a session",
    description:
      "Marks the session deleted. It leaves every listing and reads as 404, and nothing is destroyed — `POST /restore` brings it back with its participants, answers and files intact. Requires the admin role.",
    scope: "write:sessions",
    bucket: "session_writes",
    requestBody: null,
    responses: [[204, null]],
    errors: [429],
    query: [],
    open: false,
    bodyKind: "none",
  },
  {
    method: "POST",
    path: "/v1/event/{eventRef}/sessions/{sessionId}/restore",
    operationId: "restoreSession",
    tag: "Session Writes",
    summary: "Restore a deleted session",
    description: "Undoes a soft delete. Requires the admin role.",
    scope: "write:sessions",
    bucket: "session_writes",
    requestBody: null,
    responses: [[200, "SessionEnvelope"]],
    errors: [429],
    query: [],
    open: false,
    bodyKind: "none",
  },
  {
    method: "POST",
    path: "/v1/event/{eventRef}/sessions/bulk",
    operationId: "bulkSessions",
    tag: "Session Writes",
    summary: "Bulk session operations",
    description:
      "Up to 100 create/update/delete operations in one request. Each operation succeeds or fails independently and is reported by index, so a bad row never sinks the batch.",
    scope: "write:sessions",
    bucket: "session_writes",
    requestBody: "BulkOperations",
    responses: [[200, "BulkResponse"]],
    errors: [400, 429],
    query: [],
    open: false,
    bodyKind: "json",
  },
  {
    method: "PUT",
    path: "/v1/event/{eventRef}/sessions/{sessionId}/fields",
    operationId: "updateSessionFields",
    tag: "Session Writes",
    summary: "Update session custom fields",
    description:
      "Writes custom-field values without touching anything else on the session. Keys are field `internal_name`s from `GET /fields`; unknown keys are stored and returned rather than dropped.",
    scope: "write:sessions",
    bucket: "session_writes",
    requestBody: "CustomFieldsBody",
    responses: [[200, "SessionEnvelope"]],
    errors: [400, 429],
    query: [],
    open: false,
    bodyKind: "json",
  },

  // ——— Session files ———
  {
    method: "GET",
    path: "/v1/event/{eventRef}/sessions/{sessionId}/files",
    operationId: "listSessionFiles",
    tag: "Session Files",
    summary: "List files attached to a session",
    description:
      "Completed files only, latest version per file group. Incomplete two-phase uploads and soft-deleted files are omitted.",
    scope: "read:sessions",
    bucket: "entity_reads",
    requestBody: null,
    responses: [[200, "FileListEnvelope"]],
    errors: [429],
    query: [],
    open: false,
    bodyKind: "none",
  },
  {
    method: "POST",
    path: "/v1/event/{eventRef}/sessions/{sessionId}/files/upload",
    operationId: "uploadSessionFile",
    tag: "Session Files",
    summary: "Upload a session file (simple)",
    description:
      "One multipart request, up to 50 MB. The field name must be `file`. Size and MIME type are read from the bytes. For anything larger use the two-phase flow.",
    scope: "write:sessions",
    bucket: "session_writes",
    requestBody: "SessionFileUploadForm",
    responses: [[201, "FileEnvelope"]],
    errors: [400, 413, 429],
    query: [],
    open: false,
    bodyKind: "multipart",
  },
  {
    method: "POST",
    path: "/v1/event/{eventRef}/sessions/{sessionId}/files",
    operationId: "initiateSessionFileUpload",
    tag: "Session Files",
    summary: "Initiate a session file upload",
    description:
      "Two-phase upload for large files. Returns an id and an `upload.url` on this same origin: PUT the bytes there, then POST `/complete`. Unlike a presigned S3 URL the upload leg is authenticated with your ordinary API key.",
    scope: "write:sessions",
    bucket: "session_writes",
    requestBody: "SessionFileCreateBody",
    responses: [[201, "FileUploadTicket"]],
    errors: [400, 429],
    query: [],
    open: false,
    bodyKind: "json",
  },
  {
    method: "PUT",
    path: "/v1/event/{eventRef}/sessions/{sessionId}/files/{fileId}/bytes",
    operationId: "putSessionFileBytes",
    tag: "Session Files",
    summary: "Upload the bytes for an initiated file",
    description:
      "The upload leg of the two-phase flow. Send the raw file as the request body. Re-PUTting replaces the pending bytes and discards the superseded blob.",
    scope: "write:sessions",
    bucket: null,
    requestBody: null,
    responses: [[200, "FileBytesReceipt"]],
    errors: [400],
    query: [],
    open: false,
    bodyKind: "binary",
  },
  {
    method: "POST",
    path: "/v1/event/{eventRef}/sessions/{sessionId}/files/{fileId}/complete",
    operationId: "completeSessionFileUpload",
    tag: "Session Files",
    summary: "Finalize a session file upload",
    description:
      "Promotes an uploaded blob into a real attachment on the session. Fails with 400 if no bytes were received.",
    scope: "write:sessions",
    bucket: "session_writes",
    requestBody: null,
    responses: [[201, "FileEnvelope"]],
    errors: [400, 429],
    query: [],
    open: false,
    bodyKind: "none",
  },
  {
    method: "POST",
    path: "/v1/event/{eventRef}/sessions/{sessionId}/files/{fileId}/replace",
    operationId: "replaceSessionFile",
    tag: "Session Files",
    summary: "Replace session file bytes",
    description:
      "Starts a two-phase upload that supersedes an existing file, bumping its version. The previous version is retired when the replacement completes.",
    scope: "write:sessions",
    bucket: "session_writes",
    requestBody: "SessionFileCreateBody",
    responses: [[201, "FileUploadTicket"]],
    errors: [400, 429],
    query: [],
    open: false,
    bodyKind: "json",
  },
  {
    method: "PUT",
    path: "/v1/event/{eventRef}/sessions/{sessionId}/files/{fileId}",
    operationId: "updateSessionFile",
    tag: "Session Files",
    summary: "Update session file metadata",
    description:
      "Changes the display title and/or the participant the file is assigned to. Does not touch the bytes — use `/replace` for that.",
    scope: "write:sessions",
    bucket: "session_writes",
    requestBody: "SessionFileUpdateBody",
    responses: [[200, "FileEnvelope"]],
    errors: [400, 429],
    query: [],
    open: false,
    bodyKind: "json",
  },
  {
    method: "DELETE",
    path: "/v1/event/{eventRef}/sessions/{sessionId}/files/{fileId}",
    operationId: "deleteSessionFile",
    tag: "Session Files",
    summary: "Delete a session file",
    description: "Soft-deletes the attachment; the bytes are swept later.",
    scope: "write:sessions",
    bucket: "session_writes",
    requestBody: null,
    responses: [[204, null]],
    errors: [429],
    query: [],
    open: false,
    bodyKind: "none",
  },

  // ——— Speakers ———
  {
    method: "GET",
    path: "/v1/event/{eventRef}/speakers",
    operationId: "listSpeakers",
    tag: "Speakers",
    summary: "List speakers",
    description:
      "Everyone on the event's roster with the sessions they are on, ordered by surname.",
    scope: "read:contacts",
    bucket: null,
    requestBody: null,
    responses: [[200, "SpeakersPage"]],
    errors: [],
    query: ["page", "pageSize", "search", "workflow_status"],
    open: false,
    bodyKind: "none",
  },
  {
    method: "POST",
    path: "/v1/event/{eventRef}/speakers",
    operationId: "searchSpeakers",
    tag: "Speakers",
    summary: "Search speakers",
    description:
      "Same data as the list form, with the search body Sessionboard clients send.",
    scope: "read:contacts",
    bucket: null,
    requestBody: "SpeakerSearchBody",
    responses: [[200, "SpeakersPage"]],
    errors: [400],
    query: ["page", "pageSize"],
    open: false,
    bodyKind: "json",
  },
  {
    method: "GET",
    path: "/v1/event/{eventRef}/speakers/{speakerId}",
    operationId: "getSpeaker",
    tag: "Speakers",
    summary: "Get a speaker",
    description:
      "One speaker with every session they participate in, in full session shape.",
    scope: "read:contacts",
    bucket: "entity_reads",
    requestBody: null,
    responses: [[200, "SpeakerEnvelope"]],
    errors: [429],
    query: [],
    open: false,
    bodyKind: "none",
  },
  {
    method: "POST",
    path: "/v1/event/{eventRef}/speakers/create",
    operationId: "createSpeaker",
    tag: "Speakers",
    summary: "Create a speaker",
    description:
      "Adds someone to the roster. Idempotent on email within the event: creating a speaker who already exists updates their workflow status instead of duplicating them.",
    scope: "write:contacts",
    bucket: "session_writes",
    requestBody: "SpeakerWriteBody",
    responses: [[201, "SpeakerEnvelope"]],
    errors: [400, 429],
    query: [],
    open: false,
    bodyKind: "json",
  },
  {
    method: "PUT",
    path: "/v1/event/{eventRef}/speakers/{speakerId}",
    operationId: "updateSpeaker",
    tag: "Speakers",
    summary: "Update a speaker",
    description: "Partial update of a speaker's profile and workflow status.",
    scope: "write:contacts",
    bucket: "session_writes",
    requestBody: "SpeakerWriteBody",
    responses: [[200, "SpeakerEnvelope"]],
    errors: [400, 429],
    query: [],
    open: false,
    bodyKind: "json",
  },

  // ——— Submissions (pre-parity endpoint, preserved) ———
  {
    method: "GET",
    path: "/v1/event/{eventRef}/submissions",
    operationId: "listSubmissions",
    tag: "Sessions",
    summary: "List submissions",
    description:
      "Every submission for the event with its participants, in the shape this endpoint has returned since before the parity work. `POST /sessions` with `filters.isAbstract` is the richer modern equivalent.",
    scope: "read:sessions",
    bucket: null,
    requestBody: null,
    responses: [[200, "SubmissionsPage"]],
    errors: [],
    query: ["page", "pageSize"],
    open: false,
    bodyKind: "none",
  },

  // ——— Agenda ———
  {
    method: "GET",
    path: "/v1/event/{eventRef}/agenda",
    operationId: "getAgenda",
    tag: "Agenda",
    summary: "Get the agenda",
    description:
      "The whole timetable in one read: rooms, tracks, every placement, everything still unscheduled, and the live conflict list (double-booked rooms and speakers).",
    scope: "read:events",
    bucket: null,
    requestBody: null,
    responses: [[200, "AgendaEnvelope"]],
    errors: [],
    query: [],
    open: false,
    bodyKind: "none",
  },
  {
    method: "POST",
    path: "/v1/event/{eventRef}/agenda/publish",
    operationId: "publishAgenda",
    tag: "Agenda",
    summary: "Publish the agenda",
    description:
      "Opens the public programme. Until this is called the public pages render “Schedule coming soon” however much is scheduled internally. Requires the admin role.",
    scope: "write:events",
    bucket: "event_writes",
    requestBody: null,
    responses: [[200, "EventEnvelope"]],
    errors: [429],
    query: [],
    open: false,
    bodyKind: "none",
  },
  {
    method: "POST",
    path: "/v1/event/{eventRef}/agenda/unpublish",
    operationId: "unpublishAgenda",
    tag: "Agenda",
    summary: "Unpublish the agenda",
    description: "Takes the public programme back down. Requires the admin role.",
    scope: "write:events",
    bucket: "event_writes",
    requestBody: null,
    responses: [[200, "EventEnvelope"]],
    errors: [429],
    query: [],
    open: false,
    bodyKind: "none",
  },

  // ——— Webhooks ———
  {
    method: "GET",
    path: "/v1/webhooks",
    operationId: "listWebhooks",
    tag: "Webhooks",
    summary: "List webhook endpoints",
    description:
      "Every endpoint in the workspaces you belong to. Signing secrets are masked here — the full value is shown once, when the endpoint is created or its secret rotated.",
    scope: "read:events",
    bucket: null,
    requestBody: null,
    responses: [[200, "WebhookListEnvelope"]],
    errors: [],
    query: ["event"],
    open: false,
    bodyKind: "none",
  },
  {
    method: "POST",
    path: "/v1/webhooks",
    operationId: "createWebhook",
    tag: "Webhooks",
    summary: "Create a webhook endpoint",
    description:
      "Subscribes an HTTPS endpoint to a set of event types (`[\"*\"]` for all). The response is the only time the signing secret is returned in full. Requires the admin role.",
    scope: "write:events",
    bucket: "event_writes",
    requestBody: "WebhookWriteBody",
    responses: [[201, "WebhookEnvelope"]],
    errors: [400, 429],
    query: [],
    open: false,
    bodyKind: "json",
  },
  {
    method: "GET",
    path: "/v1/webhooks/{webhookId}",
    operationId: "getWebhook",
    tag: "Webhooks",
    summary: "Get a webhook endpoint",
    description: "The endpoint plus its 25 most recent delivery attempts.",
    scope: "read:events",
    bucket: null,
    requestBody: null,
    responses: [[200, "WebhookDetailEnvelope"]],
    errors: [],
    query: [],
    open: false,
    bodyKind: "none",
  },
  {
    method: "PUT",
    path: "/v1/webhooks/{webhookId}",
    operationId: "updateWebhook",
    tag: "Webhooks",
    summary: "Update a webhook endpoint",
    description:
      "Change the URL, the subscribed event types, the description, or disable it. Requires the admin role.",
    scope: "write:events",
    bucket: "event_writes",
    requestBody: "WebhookWriteBody",
    responses: [[200, "WebhookEnvelope"]],
    errors: [400, 429],
    query: [],
    open: false,
    bodyKind: "json",
  },
  {
    method: "DELETE",
    path: "/v1/webhooks/{webhookId}",
    operationId: "deleteWebhook",
    tag: "Webhooks",
    summary: "Delete a webhook endpoint",
    description:
      "Removes the endpoint and its delivery log. Requires the admin role.",
    scope: "write:events",
    bucket: "event_writes",
    requestBody: null,
    responses: [[204, null]],
    errors: [429],
    query: [],
    open: false,
    bodyKind: "none",
  },
  {
    method: "POST",
    path: "/v1/webhooks/{webhookId}/test",
    operationId: "testWebhook",
    tag: "Webhooks",
    summary: "Send a test delivery",
    description:
      "Queues a signed `webhook.test` delivery so you can verify your receiver without waiting for a real change.",
    scope: "write:events",
    bucket: "event_writes",
    requestBody: null,
    responses: [[200, "WebhookTestEnvelope"]],
    errors: [429],
    query: [],
    open: false,
    bodyKind: "none",
  },
  {
    method: "POST",
    path: "/v1/webhooks/{webhookId}/rotate",
    operationId: "rotateWebhookSecret",
    tag: "Webhooks",
    summary: "Rotate the signing secret",
    description:
      "Issues a new `whsec_…` secret and returns it in full, once. Deliveries in flight are signed with whichever secret was current when they were sent.",
    scope: "write:events",
    bucket: "event_writes",
    requestBody: null,
    responses: [[200, "WebhookEnvelope"]],
    errors: [429],
    query: [],
    open: false,
    bodyKind: "none",
  },
  {
    method: "GET",
    path: "/v1/webhooks/{webhookId}/deliveries",
    operationId: "listWebhookDeliveries",
    tag: "Webhooks",
    summary: "List delivery attempts",
    description:
      "The delivery log for one endpoint, newest first, including the exact signed payload, the response status and any error.",
    scope: "read:events",
    bucket: null,
    requestBody: null,
    responses: [[200, "WebhookDeliveryListEnvelope"]],
    errors: [],
    query: ["limit"],
    open: false,
    bodyKind: "none",
  },
]
