/**
 * Destinations used across the marketing homepage.
 * Kept in one place so a URL never drifts between the nav, hero, pricing and footer.
 */
import { eventPath, formPath } from "@/lib/public-links"

/**
 * The product name and the domains shown in mock browser chrome, in ONE place.
 *
 * Nothing on this page spells the name out inline — prefer the `Logo`/`Wordmark`
 * components where a lockup fits, and these constants where prose or an
 * aria-label needs the bare string.
 */
export const PRODUCT_NAME = "Trackstage"
export const PRODUCT_APP_HOST = "trackstage.app"
export const PRODUCT_SITE_HOST = "trackstage.app"

/**
 * All public GitHub links go through /get: it live-checks whether the repo is
 * public and either forwards straight to GitHub or explains that the code
 * opens when the Kill My SaaS contest concludes (repo private until then so
 * the work can't be lifted mid-competition). Once the repo is flipped public,
 * /get becomes a pure redirect — no code change needed.
 */
export const GITHUB_URL = "/get"
export const GITHUB_LICENSE_URL = GITHUB_URL
export const GITHUB_README_URL = GITHUB_URL
export const GITHUB_ISSUES_URL = GITHUB_URL
export const SESSIONBOARD_URL = "https://www.sessionboard.com"

/**
 * Public product surfaces anyone can open without an account. These are real,
 * seeded routes (`convex/seed.ts`) — the landing page never links to a stub.
 */
export const DEMO_PORTAL_URL = "/portal"
/**
 * The seeded demo organizer account (`convex/seed.ts`), shown with a one-click
 * copy on the landing page's demo block and on the sign-in card. ONE source —
 * the login page imports these too, so the two can never drift.
 */
export const DEMO_ORGANIZER_EMAIL = "organizer@demo.sessionboard.dev"
export const DEMO_ORGANIZER_PASSWORD = "demo2026"
export const DEMO_WORKSPACE_SLUG = "ai-engineer"
export const DEMO_EVENT_SLUG = "ai-summit-2026"
export const DEMO_PROGRAM_URL = eventPath(DEMO_WORKSPACE_SLUG, DEMO_EVENT_SLUG)
/**
 * The canonical public CFP address is `/submit/:ws/:event/:form` — workspace,
 * event and form slugs nest (docs/memory/DECISIONS.md, "URL architecture is
 * fully hierarchical"). The legacy shorter shapes still redirect here, but
 * nothing we publish should point at them.
 */
export const DEMO_CFP_SLUG = "cfp"
export const DEMO_CFP_URL = formPath(
  DEMO_WORKSPACE_SLUG,
  DEMO_EVENT_SLUG,
  DEMO_CFP_SLUG,
)
/**
 * The public REST surface, served by the Convex HTTP router (`convex/http.ts`)
 * on the deployment's `.convex.site` domain. Sessions/speakers/submissions take
 * a Bearer API key; the `.ics` feed is open.
 */
export const PUBLIC_API_PREFIX = "/v1/event/{slug}"
export const PUBLIC_ICS_PATH = `${PUBLIC_API_PREFIX}/schedule.ics`
/** The MCP endpoint agents connect to (Convex HTTP router, `convex/mcp.ts`). */
export const MCP_ENDPOINT_PATH = "/mcp"
/**
 * Tool count exposed by our MCP server. Re-exported from the file generated by
 * `scripts/generate-mcp-tools.mjs`, so it cannot drift from `convex/mcp.ts`.
 */
export { MCP_TOOL_COUNT } from "@/docs/generated/mcp-tools"

/** In-page anchors. Section ids live here so nav and sections cannot drift. */
export const SECTION_IDS = {
  product: "product",
  demos: "demos",
  platform: "platform",
  openSource: "open-source",
  pricing: "pricing",
} as const

/** Props every external link on this page uses. */
export const EXTERNAL_LINK_PROPS = {
  target: "_blank",
  rel: "noreferrer",
} as const
