/**
 * Destinations used across the marketing homepage.
 * Kept in one place so a URL never drifts between the nav, hero, pricing and footer.
 */

/**
 * The product name and the domains shown in mock browser chrome, in ONE place.
 *
 * Nothing on this page spells the name out inline — prefer the `Logo`/`Wordmark`
 * components where a lockup fits, and these constants where prose or an
 * aria-label needs the bare string.
 */
export const PRODUCT_NAME = "Trackstage"
export const PRODUCT_APP_HOST = "trackstage.app"
export const PRODUCT_SITE_HOST = "trackstage.app"

export const GITHUB_URL = "https://github.com/markokraemer/trackstage"
export const GITHUB_LICENSE_URL = `${GITHUB_URL}/blob/main/LICENSE`
export const GITHUB_README_URL = `${GITHUB_URL}#readme`
export const GITHUB_ISSUES_URL = `${GITHUB_URL}/issues`
export const SESSIONBOARD_URL = "https://www.sessionboard.com"
export const KILL_MY_SAAS_POST_URL =
  "https://x.com/swyx/status/2085517544795079014"
export const LATENT_SPACE_URL = "https://www.latent.space"

/**
 * Public product surfaces anyone can open without an account. These are real,
 * seeded routes (`convex/seed.ts`) — the landing page never links to a stub.
 */
export const DEMO_CFP_URL = "/submit/cfp"
export const DEMO_PORTAL_URL = "/portal"
export const DEMO_EVENT_SLUG = "ai-summit-2026"
export const DEMO_PROGRAM_URL = `/e/${DEMO_EVENT_SLUG}`
/**
 * The public REST surface, served by the Convex HTTP router (`convex/http.ts`)
 * on the deployment's `.convex.site` domain. Sessions/speakers/submissions take
 * a Bearer API key; the `.ics` feed is open.
 */
export const PUBLIC_API_PREFIX = "/v1/event/{slug}"
export const PUBLIC_ICS_PATH = `${PUBLIC_API_PREFIX}/schedule.ics`
/** The MCP endpoint agents connect to (Convex HTTP router, `convex/mcp.ts`). */
export const MCP_ENDPOINT_PATH = "/mcp"
/**
 * Tool count exposed by our MCP server. Re-exported from the file generated by
 * `scripts/generate-mcp-tools.mjs`, so it cannot drift from `convex/mcp.ts`.
 */
export { MCP_TOOL_COUNT } from "@/docs/generated/mcp-tools"

/** In-page anchors. Section ids live here so nav and sections cannot drift. */
export const SECTION_IDS = {
  product: "product",
  demos: "demos",
  platform: "platform",
  openSource: "open-source",
  pricing: "pricing",
} as const

/** Props every external link on this page uses. */
export const EXTERNAL_LINK_PROPS = {
  target: "_blank",
  rel: "noreferrer",
} as const
