import { chromium, devices } from "@playwright/test"
const iphone = { viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, userAgent: devices["iPhone 13"].userAgent }
const browser = await chromium.launch()
const ctx = await browser.newContext({ ...iphone, storageState: "tests/e2e/.auth/organizer.json" })
const page = await ctx.newPage()
await page.goto("http://localhost:3000/app/ai-engineer/ai-summit-2026/submissions", { waitUntil: "networkidle" }).catch(() => {})
await page.waitForTimeout(3000)
await page.locator("tbody tr a").first().click()
await page.waitForTimeout(1200)
const hist = page.getByRole("tab", { name: /history/i }).first()
await hist.scrollIntoViewIfNeeded()
await hist.click()
await page.waitForTimeout(800)
await page.screenshot({ path: ".mobile-shots/drawer-history-tab.png" })
console.log("history tab reachable + clickable:", await hist.getAttribute("aria-selected") ?? await hist.getAttribute("data-active") ?? "clicked")
await browser.close()
