/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as GetRouteImport } from './routes/get'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known/oauth-authorization-server'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAccountRouteImport } from './routes/app/account'
import { Route as AppCopilotRouteImport } from './routes/app/copilot'
import { Route as AppWorkspaceRouteImport } from './routes/app/workspace'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsMcpRouteImport } from './routes/docs/mcp'
import { Route as DocsSelfHostRouteImport } from './routes/docs/self-host'
import { Route as DocsApiRouteImport } from './routes/docs_.api'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalProfileRouteImport } from './routes/portal/profile'
import { Route as PortalSubmissionsRouteImport } from './routes/portal/submissions'
import { Route as PortalTasksRouteImport } from './routes/portal/tasks'
import { Route as ReviewTokenRouteImport } from './routes/review/$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppWorkspaceSlugIndexRouteImport } from './routes/app/$workspaceSlug/index'
import { Route as AppWorkspaceSlugEventSlugRouteRouteImport } from './routes/app/$workspaceSlug/$eventSlug/route'
import { Route as AppWorkspaceSlugWorkspaceRouteImport } from './routes/app/$workspaceSlug/workspace'
import { Route as AppAgendaIndexRouteImport } from './routes/app/agenda/index'
import { Route as AppCommunicationsIndexRouteImport } from './routes/app/communications/index'
import { Route as AppEmbedsIndexRouteImport } from './routes/app/embeds/index'
import { Route as AppEvaluationIndexRouteImport } from './routes/app/evaluation/index'
import { Route as AppEvaluationPlanIdRouteImport } from './routes/app/evaluation/$planId'
import { Route as AppEventsIndexRouteImport } from './routes/app/events/index'
import { Route as AppFilesIndexRouteImport } from './routes/app/files/index'
import { Route as AppFormsIndexRouteImport } from './routes/app/forms/index'
import { Route as AppFormsFormIdRouteImport } from './routes/app/forms/$formId'
import { Route as AppFormsNewRouteImport } from './routes/app/forms/new'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppSettingsActivityRouteImport } from './routes/app/settings/activity'
import { Route as AppSettingsApiMcpRouteImport } from './routes/app/settings/api-mcp'
import { Route as AppSettingsFieldsAndOptionsRouteImport } from './routes/app/settings/fields-and-options'
import { Route as AppSettingsIntegrationsRouteImport } from './routes/app/settings/integrations'
import { Route as AppSettingsRoomsAndTracksRouteImport } from './routes/app/settings/rooms-and-tracks'
import { Route as AppSettingsStatusesRouteImport } from './routes/app/settings/statuses'
import { Route as AppSpeakersIndexRouteImport } from './routes/app/speakers/index'
import { Route as AppSubmissionsIndexRouteImport } from './routes/app/submissions/index'
import { Route as DocsGuideAiCopilotRouteImport } from './routes/docs/guide/ai-copilot'
import { Route as DocsGuideAirtableSyncRouteImport } from './routes/docs/guide/airtable-sync'
import { Route as DocsGuideBuildTheAgendaRouteImport } from './routes/docs/guide/build-the-agenda'
import { Route as DocsGuideChaseSpeakersRouteImport } from './routes/docs/guide/chase-speakers'
import { Route as DocsGuideCreateACfpFormRouteImport } from './routes/docs/guide/create-a-cfp-form'
import { Route as DocsGuideGettingStartedRouteImport } from './routes/docs/guide/getting-started'
import { Route as DocsGuidePublishYourProgramRouteImport } from './routes/docs/guide/publish-your-program'
import { Route as DocsGuideReviewAndDecideRouteImport } from './routes/docs/guide/review-and-decide'
import { Route as DocsGuideShareAndCollectRouteImport } from './routes/docs/guide/share-and-collect'
import { Route as DocsGuideSpeakerPortalRouteImport } from './routes/docs/guide/speaker-portal'
import { Route as DocsGuideTeamAndWorkspacesRouteImport } from './routes/docs/guide/team-and-workspaces'
import { Route as EWorkspaceSlugIndexRouteImport } from './routes/e/$workspaceSlug/index'
import { Route as EWorkspaceSlugEventSlugRouteRouteImport } from './routes/e/$workspaceSlug/$eventSlug/route'
import { Route as PortalTTokenRouteImport } from './routes/portal/t.$token'
import { Route as SubmitWorkspaceSlugIndexRouteImport } from './routes/submit/$workspaceSlug/index'
import { Route as AppWorkspaceSlugEventSlugIndexRouteImport } from './routes/app/$workspaceSlug/$eventSlug/index'
import { Route as AppWorkspaceSlugEventSlugSettingsRouteRouteImport } from './routes/app/$workspaceSlug/$eventSlug/settings/route'
import { Route as EWorkspaceSlugEventSlugIndexRouteImport } from './routes/e/$workspaceSlug/$eventSlug/index'
import { Route as EWorkspaceSlugEventSlugSplatRouteImport } from './routes/e/$workspaceSlug/$eventSlug/$'
import { Route as EWorkspaceSlugEventSlugMyScheduleRouteImport } from './routes/e/$workspaceSlug/$eventSlug/my-schedule'
import { Route as EWorkspaceSlugEventSlugSpeakersRouteImport } from './routes/e/$workspaceSlug/$eventSlug/speakers'
import { Route as SubmitWorkspaceSlugEventSlugIndexRouteImport } from './routes/submit/$workspaceSlug/$eventSlug/index'
import { Route as SubmitWorkspaceSlugEventSlugFormSlugRouteImport } from './routes/submit/$workspaceSlug/$eventSlug/$formSlug'
import { Route as AppWorkspaceSlugEventSlugAgendaIndexRouteImport } from './routes/app/$workspaceSlug/$eventSlug/agenda/index'
import { Route as AppWorkspaceSlugEventSlugCommunicationsIndexRouteImport } from './routes/app/$workspaceSlug/$eventSlug/communications/index'
import { Route as AppWorkspaceSlugEventSlugEmbedsIndexRouteImport } from './routes/app/$workspaceSlug/$eventSlug/embeds/index'
import { Route as AppWorkspaceSlugEventSlugEvaluationIndexRouteImport } from './routes/app/$workspaceSlug/$eventSlug/evaluation/index'
import { Route as AppWorkspaceSlugEventSlugEvaluationPlanIdRouteImport } from './routes/app/$workspaceSlug/$eventSlug/evaluation/$planId'
import { Route as AppWorkspaceSlugEventSlugFilesIndexRouteImport } from './routes/app/$workspaceSlug/$eventSlug/files/index'
import { Route as AppWorkspaceSlugEventSlugFormsIndexRouteImport } from './routes/app/$workspaceSlug/$eventSlug/forms/index'
import { Route as AppWorkspaceSlugEventSlugFormsFormIdRouteImport } from './routes/app/$workspaceSlug/$eventSlug/forms/$formId'
import { Route as AppWorkspaceSlugEventSlugFormsNewRouteImport } from './routes/app/$workspaceSlug/$eventSlug/forms/new'
import { Route as AppWorkspaceSlugEventSlugSettingsIndexRouteImport } from './routes/app/$workspaceSlug/$eventSlug/settings/index'
import { Route as AppWorkspaceSlugEventSlugSettingsActivityRouteImport } from './routes/app/$workspaceSlug/$eventSlug/settings/activity'
import { Route as AppWorkspaceSlugEventSlugSettingsApiMcpRouteImport } from './routes/app/$workspaceSlug/$eventSlug/settings/api-mcp'
import { Route as AppWorkspaceSlugEventSlugSettingsFieldsAndOptionsRouteImport } from './routes/app/$workspaceSlug/$eventSlug/settings/fields-and-options'
import { Route as AppWorkspaceSlugEventSlugSettingsIntegrationsRouteImport } from './routes/app/$workspaceSlug/$eventSlug/settings/integrations'
import { Route as AppWorkspaceSlugEventSlugSettingsRoomsAndTracksRouteImport } from './routes/app/$workspaceSlug/$eventSlug/settings/rooms-and-tracks'
import { Route as AppWorkspaceSlugEventSlugSettingsStatusesRouteImport } from './routes/app/$workspaceSlug/$eventSlug/settings/statuses'
import { Route as AppWorkspaceSlugEventSlugSettingsTeamRouteImport } from './routes/app/$workspaceSlug/$eventSlug/settings/team'
import { Route as AppWorkspaceSlugEventSlugSpeakersIndexRouteImport } from './routes/app/$workspaceSlug/$eventSlug/speakers/index'
import { Route as AppWorkspaceSlugEventSlugSubmissionsIndexRouteImport } from './routes/app/$workspaceSlug/$eventSlug/submissions/index'
import { Route as EWorkspaceSlugEventSlugItineraryPersonIdRouteImport } from './routes/e/$workspaceSlug/$eventSlug/itinerary/$personId'
import { Route as EWorkspaceSlugEventSlugSessionsIndexRouteImport } from './routes/e/$workspaceSlug/$eventSlug/sessions/index'
import { Route as EWorkspaceSlugEventSlugSessionsSessionIdRouteImport } from './routes/e/$workspaceSlug/$eventSlug/sessions/$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const GetRoute = GetRouteImport.update({
  id: '/get',
  path: '/get',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRouteRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsMcpRoute = DocsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsSelfHostRoute = DocsSelfHostRouteImport.update({
  id: '/self-host',
  path: '/self-host',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/docs_/api',
  path: '/docs/api',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalSubmissionsRoute = PortalSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalTasksRoute = PortalTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => PortalRouteRoute,
} as any)
const ReviewTokenRoute = ReviewTokenRouteImport.update({
  id: '/review/$token',
  path: '/review/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceSlugIndexRoute = AppWorkspaceSlugIndexRouteImport.update({
  id: '/$workspaceSlug/',
  path: '/$workspaceSlug/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspaceSlugEventSlugRouteRoute =
  AppWorkspaceSlugEventSlugRouteRouteImport.update({
    id: '/$workspaceSlug/$eventSlug',
    path: '/$workspaceSlug/$eventSlug',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppWorkspaceSlugWorkspaceRoute =
  AppWorkspaceSlugWorkspaceRouteImport.update({
    id: '/$workspaceSlug/workspace',
    path: '/$workspaceSlug/workspace',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppAgendaIndexRoute = AppAgendaIndexRouteImport.update({
  id: '/agenda/',
  path: '/agenda/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCommunicationsIndexRoute = AppCommunicationsIndexRouteImport.update({
  id: '/communications/',
  path: '/communications/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEmbedsIndexRoute = AppEmbedsIndexRouteImport.update({
  id: '/embeds/',
  path: '/embeds/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEvaluationIndexRoute = AppEvaluationIndexRouteImport.update({
  id: '/evaluation/',
  path: '/evaluation/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEvaluationPlanIdRoute = AppEvaluationPlanIdRouteImport.update({
  id: '/evaluation/$planId',
  path: '/evaluation/$planId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFilesIndexRoute = AppFilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFormsIndexRoute = AppFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFormsFormIdRoute = AppFormsFormIdRouteImport.update({
  id: '/forms/$formId',
  path: '/forms/$formId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFormsNewRoute = AppFormsNewRouteImport.update({
  id: '/forms/new',
  path: '/forms/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsActivityRoute = AppSettingsActivityRouteImport.update({
  id: '/settings/activity',
  path: '/settings/activity',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsApiMcpRoute = AppSettingsApiMcpRouteImport.update({
  id: '/settings/api-mcp',
  path: '/settings/api-mcp',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsFieldsAndOptionsRoute =
  AppSettingsFieldsAndOptionsRouteImport.update({
    id: '/settings/fields-and-options',
    path: '/settings/fields-and-options',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppSettingsIntegrationsRoute = AppSettingsIntegrationsRouteImport.update({
  id: '/settings/integrations',
  path: '/settings/integrations',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoomsAndTracksRoute =
  AppSettingsRoomsAndTracksRouteImport.update({
    id: '/settings/rooms-and-tracks',
    path: '/settings/rooms-and-tracks',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppSettingsStatusesRoute = AppSettingsStatusesRouteImport.update({
  id: '/settings/statuses',
  path: '/settings/statuses',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSpeakersIndexRoute = AppSpeakersIndexRouteImport.update({
  id: '/speakers/',
  path: '/speakers/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSubmissionsIndexRoute = AppSubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => AppRouteRoute,
} as any)
const DocsGuideAiCopilotRoute = DocsGuideAiCopilotRouteImport.update({
  id: '/guide/ai-copilot',
  path: '/guide/ai-copilot',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsGuideAirtableSyncRoute = DocsGuideAirtableSyncRouteImport.update({
  id: '/guide/airtable-sync',
  path: '/guide/airtable-sync',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsGuideBuildTheAgendaRoute = DocsGuideBuildTheAgendaRouteImport.update({
  id: '/guide/build-the-agenda',
  path: '/guide/build-the-agenda',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsGuideChaseSpeakersRoute = DocsGuideChaseSpeakersRouteImport.update({
  id: '/guide/chase-speakers',
  path: '/guide/chase-speakers',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsGuideCreateACfpFormRoute = DocsGuideCreateACfpFormRouteImport.update({
  id: '/guide/create-a-cfp-form',
  path: '/guide/create-a-cfp-form',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsGuideGettingStartedRoute = DocsGuideGettingStartedRouteImport.update({
  id: '/guide/getting-started',
  path: '/guide/getting-started',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsGuidePublishYourProgramRoute =
  DocsGuidePublishYourProgramRouteImport.update({
    id: '/guide/publish-your-program',
    path: '/guide/publish-your-program',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsGuideReviewAndDecideRoute =
  DocsGuideReviewAndDecideRouteImport.update({
    id: '/guide/review-and-decide',
    path: '/guide/review-and-decide',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsGuideShareAndCollectRoute =
  DocsGuideShareAndCollectRouteImport.update({
    id: '/guide/share-and-collect',
    path: '/guide/share-and-collect',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsGuideSpeakerPortalRoute = DocsGuideSpeakerPortalRouteImport.update({
  id: '/guide/speaker-portal',
  path: '/guide/speaker-portal',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsGuideTeamAndWorkspacesRoute =
  DocsGuideTeamAndWorkspacesRouteImport.update({
    id: '/guide/team-and-workspaces',
    path: '/guide/team-and-workspaces',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const EWorkspaceSlugIndexRoute = EWorkspaceSlugIndexRouteImport.update({
  id: '/e/$workspaceSlug/',
  path: '/e/$workspaceSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const EWorkspaceSlugEventSlugRouteRoute =
  EWorkspaceSlugEventSlugRouteRouteImport.update({
    id: '/e/$workspaceSlug/$eventSlug',
    path: '/e/$workspaceSlug/$eventSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalTTokenRoute = PortalTTokenRouteImport.update({
  id: '/t/$token',
  path: '/t/$token',
  getParentRoute: () => PortalRouteRoute,
} as any)
const SubmitWorkspaceSlugIndexRoute =
  SubmitWorkspaceSlugIndexRouteImport.update({
    id: '/submit/$workspaceSlug/',
    path: '/submit/$workspaceSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkspaceSlugEventSlugIndexRoute =
  AppWorkspaceSlugEventSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceSlugEventSlugRouteRoute,
  } as any)
const AppWorkspaceSlugEventSlugSettingsRouteRoute =
  AppWorkspaceSlugEventSlugSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppWorkspaceSlugEventSlugRouteRoute,
  } as any)
const EWorkspaceSlugEventSlugIndexRoute =
  EWorkspaceSlugEventSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EWorkspaceSlugEventSlugRouteRoute,
  } as any)
const EWorkspaceSlugEventSlugSplatRoute =
  EWorkspaceSlugEventSlugSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => EWorkspaceSlugEventSlugRouteRoute,
  } as any)
const EWorkspaceSlugEventSlugMyScheduleRoute =
  EWorkspaceSlugEventSlugMyScheduleRouteImport.update({
    id: '/my-schedule',
    path: '/my-schedule',
    getParentRoute: () => EWorkspaceSlugEventSlugRouteRoute,
  } as any)
const EWorkspaceSlugEventSlugSpeakersRoute =
  EWorkspaceSlugEventSlugSpeakersRouteImport.update({
    id: '/speakers',
    path: '/speakers',
    getParentRoute: () => EWorkspaceSlugEventSlugRouteRoute,
  } as any)
const SubmitWorkspaceSlugEventSlugIndexRoute =
  SubmitWorkspaceSlugEventSlugIndexRouteImport.update({
    id: '/submit/$workspaceSlug/$eventSlug/',
    path: '/submit/$workspaceSlug/$eventSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SubmitWorkspaceSlugEventSlugFormSlugRoute =
  SubmitWorkspaceSlugEventSlugFormSlugRouteImport.update({
    id: '/submit/$workspaceSlug/$eventSlug/$formSlug',
    path: '/submit/$workspaceSlug/$eventSlug/$formSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkspaceSlugEventSlugAgendaIndexRoute =
  AppWorkspaceSlugEventSlugAgendaIndexRouteImport.update({
    id: '/agenda/',
    path: '/agenda/',
    getParentRoute: () => AppWorkspaceSlugEventSlugRouteRoute,
  } as any)
const AppWorkspaceSlugEventSlugCommunicationsIndexRoute =
  AppWorkspaceSlugEventSlugCommunicationsIndexRouteImport.update({
    id: '/communications/',
    path: '/communications/',
    getParentRoute: () => AppWorkspaceSlugEventSlugRouteRoute,
  } as any)
const AppWorkspaceSlugEventSlugEmbedsIndexRoute =
  AppWorkspaceSlugEventSlugEmbedsIndexRouteImport.update({
    id: '/embeds/',
    path: '/embeds/',
    getParentRoute: () => AppWorkspaceSlugEventSlugRouteRoute,
  } as any)
const AppWorkspaceSlugEventSlugEvaluationIndexRoute =
  AppWorkspaceSlugEventSlugEvaluationIndexRouteImport.update({
    id: '/evaluation/',
    path: '/evaluation/',
    getParentRoute: () => AppWorkspaceSlugEventSlugRouteRoute,
  } as any)
const AppWorkspaceSlugEventSlugEvaluationPlanIdRoute =
  AppWorkspaceSlugEventSlugEvaluationPlanIdRouteImport.update({
    id: '/evaluation/$planId',
    path: '/evaluation/$planId',
    getParentRoute: () => AppWorkspaceSlugEventSlugRouteRoute,
  } as any)
const AppWorkspaceSlugEventSlugFilesIndexRoute =
  AppWorkspaceSlugEventSlugFilesIndexRouteImport.update({
    id: '/files/',
    path: '/files/',
    getParentRoute: () => AppWorkspaceSlugEventSlugRouteRoute,
  } as any)
const AppWorkspaceSlugEventSlugFormsIndexRoute =
  AppWorkspaceSlugEventSlugFormsIndexRouteImport.update({
    id: '/forms/',
    path: '/forms/',
    getParentRoute: () => AppWorkspaceSlugEventSlugRouteRoute,
  } as any)
const AppWorkspaceSlugEventSlugFormsFormIdRoute =
  AppWorkspaceSlugEventSlugFormsFormIdRouteImport.update({
    id: '/forms/$formId',
    path: '/forms/$formId',
    getParentRoute: () => AppWorkspaceSlugEventSlugRouteRoute,
  } as any)
const AppWorkspaceSlugEventSlugFormsNewRoute =
  AppWorkspaceSlugEventSlugFormsNewRouteImport.update({
    id: '/forms/new',
    path: '/forms/new',
    getParentRoute: () => AppWorkspaceSlugEventSlugRouteRoute,
  } as any)
const AppWorkspaceSlugEventSlugSettingsIndexRoute =
  AppWorkspaceSlugEventSlugSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceSlugEventSlugSettingsRouteRoute,
  } as any)
const AppWorkspaceSlugEventSlugSettingsActivityRoute =
  AppWorkspaceSlugEventSlugSettingsActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AppWorkspaceSlugEventSlugSettingsRouteRoute,
  } as any)
const AppWorkspaceSlugEventSlugSettingsApiMcpRoute =
  AppWorkspaceSlugEventSlugSettingsApiMcpRouteImport.update({
    id: '/api-mcp',
    path: '/api-mcp',
    getParentRoute: () => AppWorkspaceSlugEventSlugSettingsRouteRoute,
  } as any)
const AppWorkspaceSlugEventSlugSettingsFieldsAndOptionsRoute =
  AppWorkspaceSlugEventSlugSettingsFieldsAndOptionsRouteImport.update({
    id: '/fields-and-options',
    path: '/fields-and-options',
    getParentRoute: () => AppWorkspaceSlugEventSlugSettingsRouteRoute,
  } as any)
const AppWorkspaceSlugEventSlugSettingsIntegrationsRoute =
  AppWorkspaceSlugEventSlugSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AppWorkspaceSlugEventSlugSettingsRouteRoute,
  } as any)
const AppWorkspaceSlugEventSlugSettingsRoomsAndTracksRoute =
  AppWorkspaceSlugEventSlugSettingsRoomsAndTracksRouteImport.update({
    id: '/rooms-and-tracks',
    path: '/rooms-and-tracks',
    getParentRoute: () => AppWorkspaceSlugEventSlugSettingsRouteRoute,
  } as any)
const AppWorkspaceSlugEventSlugSettingsStatusesRoute =
  AppWorkspaceSlugEventSlugSettingsStatusesRouteImport.update({
    id: '/statuses',
    path: '/statuses',
    getParentRoute: () => AppWorkspaceSlugEventSlugSettingsRouteRoute,
  } as any)
const AppWorkspaceSlugEventSlugSettingsTeamRoute =
  AppWorkspaceSlugEventSlugSettingsTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AppWorkspaceSlugEventSlugSettingsRouteRoute,
  } as any)
const AppWorkspaceSlugEventSlugSpeakersIndexRoute =
  AppWorkspaceSlugEventSlugSpeakersIndexRouteImport.update({
    id: '/speakers/',
    path: '/speakers/',
    getParentRoute: () => AppWorkspaceSlugEventSlugRouteRoute,
  } as any)
const AppWorkspaceSlugEventSlugSubmissionsIndexRoute =
  AppWorkspaceSlugEventSlugSubmissionsIndexRouteImport.update({
    id: '/submissions/',
    path: '/submissions/',
    getParentRoute: () => AppWorkspaceSlugEventSlugRouteRoute,
  } as any)
const EWorkspaceSlugEventSlugItineraryPersonIdRoute =
  EWorkspaceSlugEventSlugItineraryPersonIdRouteImport.update({
    id: '/itinerary/$personId',
    path: '/itinerary/$personId',
    getParentRoute: () => EWorkspaceSlugEventSlugRouteRoute,
  } as any)
const EWorkspaceSlugEventSlugSessionsIndexRoute =
  EWorkspaceSlugEventSlugSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => EWorkspaceSlugEventSlugRouteRoute,
  } as any)
const EWorkspaceSlugEventSlugSessionsSessionIdRoute =
  EWorkspaceSlugEventSlugSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => EWorkspaceSlugEventSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/confirm-email': typeof ConfirmEmailRoute
  '/design-system': typeof DesignSystemRoute
  '/get': typeof GetRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/api/chat': typeof ApiChatRoute
  '/app/account': typeof AppAccountRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/docs/self-host': typeof DocsSelfHostRoute
  '/docs/api': typeof DocsApiRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/submissions': typeof PortalSubmissionsRoute
  '/portal/tasks': typeof PortalTasksRoute
  '/review/$token': typeof ReviewTokenRoute
  '/app/': typeof AppIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/app/$workspaceSlug/$eventSlug': typeof AppWorkspaceSlugEventSlugRouteRouteWithChildren
  '/e/$workspaceSlug/$eventSlug': typeof EWorkspaceSlugEventSlugRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$workspaceSlug/workspace': typeof AppWorkspaceSlugWorkspaceRoute
  '/app/evaluation/$planId': typeof AppEvaluationPlanIdRoute
  '/app/forms/$formId': typeof AppFormsFormIdRoute
  '/app/forms/new': typeof AppFormsNewRoute
  '/app/settings/activity': typeof AppSettingsActivityRoute
  '/app/settings/api-mcp': typeof AppSettingsApiMcpRoute
  '/app/settings/fields-and-options': typeof AppSettingsFieldsAndOptionsRoute
  '/app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/app/settings/rooms-and-tracks': typeof AppSettingsRoomsAndTracksRoute
  '/app/settings/statuses': typeof AppSettingsStatusesRoute
  '/docs/guide/ai-copilot': typeof DocsGuideAiCopilotRoute
  '/docs/guide/airtable-sync': typeof DocsGuideAirtableSyncRoute
  '/docs/guide/build-the-agenda': typeof DocsGuideBuildTheAgendaRoute
  '/docs/guide/chase-speakers': typeof DocsGuideChaseSpeakersRoute
  '/docs/guide/create-a-cfp-form': typeof DocsGuideCreateACfpFormRoute
  '/docs/guide/getting-started': typeof DocsGuideGettingStartedRoute
  '/docs/guide/publish-your-program': typeof DocsGuidePublishYourProgramRoute
  '/docs/guide/review-and-decide': typeof DocsGuideReviewAndDecideRoute
  '/docs/guide/share-and-collect': typeof DocsGuideShareAndCollectRoute
  '/docs/guide/speaker-portal': typeof DocsGuideSpeakerPortalRoute
  '/docs/guide/team-and-workspaces': typeof DocsGuideTeamAndWorkspacesRoute
  '/portal/t/$token': typeof PortalTTokenRoute
  '/app/$workspaceSlug/': typeof AppWorkspaceSlugIndexRoute
  '/app/agenda/': typeof AppAgendaIndexRoute
  '/app/communications/': typeof AppCommunicationsIndexRoute
  '/app/embeds/': typeof AppEmbedsIndexRoute
  '/app/evaluation/': typeof AppEvaluationIndexRoute
  '/app/events/': typeof AppEventsIndexRoute
  '/app/files/': typeof AppFilesIndexRoute
  '/app/forms/': typeof AppFormsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/speakers/': typeof AppSpeakersIndexRoute
  '/app/submissions/': typeof AppSubmissionsIndexRoute
  '/e/$workspaceSlug/': typeof EWorkspaceSlugIndexRoute
  '/submit/$workspaceSlug/': typeof SubmitWorkspaceSlugIndexRoute
  '/app/$workspaceSlug/$eventSlug/settings': typeof AppWorkspaceSlugEventSlugSettingsRouteRouteWithChildren
  '/e/$workspaceSlug/$eventSlug/$': typeof EWorkspaceSlugEventSlugSplatRoute
  '/e/$workspaceSlug/$eventSlug/my-schedule': typeof EWorkspaceSlugEventSlugMyScheduleRoute
  '/e/$workspaceSlug/$eventSlug/speakers': typeof EWorkspaceSlugEventSlugSpeakersRoute
  '/submit/$workspaceSlug/$eventSlug/$formSlug': typeof SubmitWorkspaceSlugEventSlugFormSlugRoute
  '/app/$workspaceSlug/$eventSlug/': typeof AppWorkspaceSlugEventSlugIndexRoute
  '/e/$workspaceSlug/$eventSlug/': typeof EWorkspaceSlugEventSlugIndexRoute
  '/submit/$workspaceSlug/$eventSlug/': typeof SubmitWorkspaceSlugEventSlugIndexRoute
  '/app/$workspaceSlug/$eventSlug/evaluation/$planId': typeof AppWorkspaceSlugEventSlugEvaluationPlanIdRoute
  '/app/$workspaceSlug/$eventSlug/forms/$formId': typeof AppWorkspaceSlugEventSlugFormsFormIdRoute
  '/app/$workspaceSlug/$eventSlug/forms/new': typeof AppWorkspaceSlugEventSlugFormsNewRoute
  '/app/$workspaceSlug/$eventSlug/settings/activity': typeof AppWorkspaceSlugEventSlugSettingsActivityRoute
  '/app/$workspaceSlug/$eventSlug/settings/api-mcp': typeof AppWorkspaceSlugEventSlugSettingsApiMcpRoute
  '/app/$workspaceSlug/$eventSlug/settings/fields-and-options': typeof AppWorkspaceSlugEventSlugSettingsFieldsAndOptionsRoute
  '/app/$workspaceSlug/$eventSlug/settings/integrations': typeof AppWorkspaceSlugEventSlugSettingsIntegrationsRoute
  '/app/$workspaceSlug/$eventSlug/settings/rooms-and-tracks': typeof AppWorkspaceSlugEventSlugSettingsRoomsAndTracksRoute
  '/app/$workspaceSlug/$eventSlug/settings/statuses': typeof AppWorkspaceSlugEventSlugSettingsStatusesRoute
  '/app/$workspaceSlug/$eventSlug/settings/team': typeof AppWorkspaceSlugEventSlugSettingsTeamRoute
  '/e/$workspaceSlug/$eventSlug/itinerary/$personId': typeof EWorkspaceSlugEventSlugItineraryPersonIdRoute
  '/e/$workspaceSlug/$eventSlug/sessions/$sessionId': typeof EWorkspaceSlugEventSlugSessionsSessionIdRoute
  '/app/$workspaceSlug/$eventSlug/agenda/': typeof AppWorkspaceSlugEventSlugAgendaIndexRoute
  '/app/$workspaceSlug/$eventSlug/communications/': typeof AppWorkspaceSlugEventSlugCommunicationsIndexRoute
  '/app/$workspaceSlug/$eventSlug/embeds/': typeof AppWorkspaceSlugEventSlugEmbedsIndexRoute
  '/app/$workspaceSlug/$eventSlug/evaluation/': typeof AppWorkspaceSlugEventSlugEvaluationIndexRoute
  '/app/$workspaceSlug/$eventSlug/files/': typeof AppWorkspaceSlugEventSlugFilesIndexRoute
  '/app/$workspaceSlug/$eventSlug/forms/': typeof AppWorkspaceSlugEventSlugFormsIndexRoute
  '/app/$workspaceSlug/$eventSlug/settings/': typeof AppWorkspaceSlugEventSlugSettingsIndexRoute
  '/app/$workspaceSlug/$eventSlug/speakers/': typeof AppWorkspaceSlugEventSlugSpeakersIndexRoute
  '/app/$workspaceSlug/$eventSlug/submissions/': typeof AppWorkspaceSlugEventSlugSubmissionsIndexRoute
  '/e/$workspaceSlug/$eventSlug/sessions/': typeof EWorkspaceSlugEventSlugSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/design-system': typeof DesignSystemRoute
  '/get': typeof GetRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/api/chat': typeof ApiChatRoute
  '/app/account': typeof AppAccountRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/docs/self-host': typeof DocsSelfHostRoute
  '/docs/api': typeof DocsApiRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/submissions': typeof PortalSubmissionsRoute
  '/portal/tasks': typeof PortalTasksRoute
  '/review/$token': typeof ReviewTokenRoute
  '/app': typeof AppIndexRoute
  '/docs': typeof DocsIndexRoute
  '/portal': typeof PortalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$workspaceSlug/workspace': typeof AppWorkspaceSlugWorkspaceRoute
  '/app/evaluation/$planId': typeof AppEvaluationPlanIdRoute
  '/app/forms/$formId': typeof AppFormsFormIdRoute
  '/app/forms/new': typeof AppFormsNewRoute
  '/app/settings/activity': typeof AppSettingsActivityRoute
  '/app/settings/api-mcp': typeof AppSettingsApiMcpRoute
  '/app/settings/fields-and-options': typeof AppSettingsFieldsAndOptionsRoute
  '/app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/app/settings/rooms-and-tracks': typeof AppSettingsRoomsAndTracksRoute
  '/app/settings/statuses': typeof AppSettingsStatusesRoute
  '/docs/guide/ai-copilot': typeof DocsGuideAiCopilotRoute
  '/docs/guide/airtable-sync': typeof DocsGuideAirtableSyncRoute
  '/docs/guide/build-the-agenda': typeof DocsGuideBuildTheAgendaRoute
  '/docs/guide/chase-speakers': typeof DocsGuideChaseSpeakersRoute
  '/docs/guide/create-a-cfp-form': typeof DocsGuideCreateACfpFormRoute
  '/docs/guide/getting-started': typeof DocsGuideGettingStartedRoute
  '/docs/guide/publish-your-program': typeof DocsGuidePublishYourProgramRoute
  '/docs/guide/review-and-decide': typeof DocsGuideReviewAndDecideRoute
  '/docs/guide/share-and-collect': typeof DocsGuideShareAndCollectRoute
  '/docs/guide/speaker-portal': typeof DocsGuideSpeakerPortalRoute
  '/docs/guide/team-and-workspaces': typeof DocsGuideTeamAndWorkspacesRoute
  '/portal/t/$token': typeof PortalTTokenRoute
  '/app/$workspaceSlug': typeof AppWorkspaceSlugIndexRoute
  '/app/agenda': typeof AppAgendaIndexRoute
  '/app/communications': typeof AppCommunicationsIndexRoute
  '/app/embeds': typeof AppEmbedsIndexRoute
  '/app/evaluation': typeof AppEvaluationIndexRoute
  '/app/events': typeof AppEventsIndexRoute
  '/app/files': typeof AppFilesIndexRoute
  '/app/forms': typeof AppFormsIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/speakers': typeof AppSpeakersIndexRoute
  '/app/submissions': typeof AppSubmissionsIndexRoute
  '/e/$workspaceSlug': typeof EWorkspaceSlugIndexRoute
  '/submit/$workspaceSlug': typeof SubmitWorkspaceSlugIndexRoute
  '/e/$workspaceSlug/$eventSlug/$': typeof EWorkspaceSlugEventSlugSplatRoute
  '/e/$workspaceSlug/$eventSlug/my-schedule': typeof EWorkspaceSlugEventSlugMyScheduleRoute
  '/e/$workspaceSlug/$eventSlug/speakers': typeof EWorkspaceSlugEventSlugSpeakersRoute
  '/submit/$workspaceSlug/$eventSlug/$formSlug': typeof SubmitWorkspaceSlugEventSlugFormSlugRoute
  '/app/$workspaceSlug/$eventSlug': typeof AppWorkspaceSlugEventSlugIndexRoute
  '/e/$workspaceSlug/$eventSlug': typeof EWorkspaceSlugEventSlugIndexRoute
  '/submit/$workspaceSlug/$eventSlug': typeof SubmitWorkspaceSlugEventSlugIndexRoute
  '/app/$workspaceSlug/$eventSlug/evaluation/$planId': typeof AppWorkspaceSlugEventSlugEvaluationPlanIdRoute
  '/app/$workspaceSlug/$eventSlug/forms/$formId': typeof AppWorkspaceSlugEventSlugFormsFormIdRoute
  '/app/$workspaceSlug/$eventSlug/forms/new': typeof AppWorkspaceSlugEventSlugFormsNewRoute
  '/app/$workspaceSlug/$eventSlug/settings/activity': typeof AppWorkspaceSlugEventSlugSettingsActivityRoute
  '/app/$workspaceSlug/$eventSlug/settings/api-mcp': typeof AppWorkspaceSlugEventSlugSettingsApiMcpRoute
  '/app/$workspaceSlug/$eventSlug/settings/fields-and-options': typeof AppWorkspaceSlugEventSlugSettingsFieldsAndOptionsRoute
  '/app/$workspaceSlug/$eventSlug/settings/integrations': typeof AppWorkspaceSlugEventSlugSettingsIntegrationsRoute
  '/app/$workspaceSlug/$eventSlug/settings/rooms-and-tracks': typeof AppWorkspaceSlugEventSlugSettingsRoomsAndTracksRoute
  '/app/$workspaceSlug/$eventSlug/settings/statuses': typeof AppWorkspaceSlugEventSlugSettingsStatusesRoute
  '/app/$workspaceSlug/$eventSlug/settings/team': typeof AppWorkspaceSlugEventSlugSettingsTeamRoute
  '/e/$workspaceSlug/$eventSlug/itinerary/$personId': typeof EWorkspaceSlugEventSlugItineraryPersonIdRoute
  '/e/$workspaceSlug/$eventSlug/sessions/$sessionId': typeof EWorkspaceSlugEventSlugSessionsSessionIdRoute
  '/app/$workspaceSlug/$eventSlug/agenda': typeof AppWorkspaceSlugEventSlugAgendaIndexRoute
  '/app/$workspaceSlug/$eventSlug/communications': typeof AppWorkspaceSlugEventSlugCommunicationsIndexRoute
  '/app/$workspaceSlug/$eventSlug/embeds': typeof AppWorkspaceSlugEventSlugEmbedsIndexRoute
  '/app/$workspaceSlug/$eventSlug/evaluation': typeof AppWorkspaceSlugEventSlugEvaluationIndexRoute
  '/app/$workspaceSlug/$eventSlug/files': typeof AppWorkspaceSlugEventSlugFilesIndexRoute
  '/app/$workspaceSlug/$eventSlug/forms': typeof AppWorkspaceSlugEventSlugFormsIndexRoute
  '/app/$workspaceSlug/$eventSlug/settings': typeof AppWorkspaceSlugEventSlugSettingsIndexRoute
  '/app/$workspaceSlug/$eventSlug/speakers': typeof AppWorkspaceSlugEventSlugSpeakersIndexRoute
  '/app/$workspaceSlug/$eventSlug/submissions': typeof AppWorkspaceSlugEventSlugSubmissionsIndexRoute
  '/e/$workspaceSlug/$eventSlug/sessions': typeof EWorkspaceSlugEventSlugSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/confirm-email': typeof ConfirmEmailRoute
  '/design-system': typeof DesignSystemRoute
  '/get': typeof GetRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/api/chat': typeof ApiChatRoute
  '/app/account': typeof AppAccountRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/docs/self-host': typeof DocsSelfHostRoute
  '/docs_/api': typeof DocsApiRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/submissions': typeof PortalSubmissionsRoute
  '/portal/tasks': typeof PortalTasksRoute
  '/review/$token': typeof ReviewTokenRoute
  '/app/': typeof AppIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/app/$workspaceSlug/$eventSlug': typeof AppWorkspaceSlugEventSlugRouteRouteWithChildren
  '/e/$workspaceSlug/$eventSlug': typeof EWorkspaceSlugEventSlugRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$workspaceSlug/workspace': typeof AppWorkspaceSlugWorkspaceRoute
  '/app/evaluation/$planId': typeof AppEvaluationPlanIdRoute
  '/app/forms/$formId': typeof AppFormsFormIdRoute
  '/app/forms/new': typeof AppFormsNewRoute
  '/app/settings/activity': typeof AppSettingsActivityRoute
  '/app/settings/api-mcp': typeof AppSettingsApiMcpRoute
  '/app/settings/fields-and-options': typeof AppSettingsFieldsAndOptionsRoute
  '/app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/app/settings/rooms-and-tracks': typeof AppSettingsRoomsAndTracksRoute
  '/app/settings/statuses': typeof AppSettingsStatusesRoute
  '/docs/guide/ai-copilot': typeof DocsGuideAiCopilotRoute
  '/docs/guide/airtable-sync': typeof DocsGuideAirtableSyncRoute
  '/docs/guide/build-the-agenda': typeof DocsGuideBuildTheAgendaRoute
  '/docs/guide/chase-speakers': typeof DocsGuideChaseSpeakersRoute
  '/docs/guide/create-a-cfp-form': typeof DocsGuideCreateACfpFormRoute
  '/docs/guide/getting-started': typeof DocsGuideGettingStartedRoute
  '/docs/guide/publish-your-program': typeof DocsGuidePublishYourProgramRoute
  '/docs/guide/review-and-decide': typeof DocsGuideReviewAndDecideRoute
  '/docs/guide/share-and-collect': typeof DocsGuideShareAndCollectRoute
  '/docs/guide/speaker-portal': typeof DocsGuideSpeakerPortalRoute
  '/docs/guide/team-and-workspaces': typeof DocsGuideTeamAndWorkspacesRoute
  '/portal/t/$token': typeof PortalTTokenRoute
  '/app/$workspaceSlug/': typeof AppWorkspaceSlugIndexRoute
  '/app/agenda/': typeof AppAgendaIndexRoute
  '/app/communications/': typeof AppCommunicationsIndexRoute
  '/app/embeds/': typeof AppEmbedsIndexRoute
  '/app/evaluation/': typeof AppEvaluationIndexRoute
  '/app/events/': typeof AppEventsIndexRoute
  '/app/files/': typeof AppFilesIndexRoute
  '/app/forms/': typeof AppFormsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/speakers/': typeof AppSpeakersIndexRoute
  '/app/submissions/': typeof AppSubmissionsIndexRoute
  '/e/$workspaceSlug/': typeof EWorkspaceSlugIndexRoute
  '/submit/$workspaceSlug/': typeof SubmitWorkspaceSlugIndexRoute
  '/app/$workspaceSlug/$eventSlug/settings': typeof AppWorkspaceSlugEventSlugSettingsRouteRouteWithChildren
  '/e/$workspaceSlug/$eventSlug/$': typeof EWorkspaceSlugEventSlugSplatRoute
  '/e/$workspaceSlug/$eventSlug/my-schedule': typeof EWorkspaceSlugEventSlugMyScheduleRoute
  '/e/$workspaceSlug/$eventSlug/speakers': typeof EWorkspaceSlugEventSlugSpeakersRoute
  '/submit/$workspaceSlug/$eventSlug/$formSlug': typeof SubmitWorkspaceSlugEventSlugFormSlugRoute
  '/app/$workspaceSlug/$eventSlug/': typeof AppWorkspaceSlugEventSlugIndexRoute
  '/e/$workspaceSlug/$eventSlug/': typeof EWorkspaceSlugEventSlugIndexRoute
  '/submit/$workspaceSlug/$eventSlug/': typeof SubmitWorkspaceSlugEventSlugIndexRoute
  '/app/$workspaceSlug/$eventSlug/evaluation/$planId': typeof AppWorkspaceSlugEventSlugEvaluationPlanIdRoute
  '/app/$workspaceSlug/$eventSlug/forms/$formId': typeof AppWorkspaceSlugEventSlugFormsFormIdRoute
  '/app/$workspaceSlug/$eventSlug/forms/new': typeof AppWorkspaceSlugEventSlugFormsNewRoute
  '/app/$workspaceSlug/$eventSlug/settings/activity': typeof AppWorkspaceSlugEventSlugSettingsActivityRoute
  '/app/$workspaceSlug/$eventSlug/settings/api-mcp': typeof AppWorkspaceSlugEventSlugSettingsApiMcpRoute
  '/app/$workspaceSlug/$eventSlug/settings/fields-and-options': typeof AppWorkspaceSlugEventSlugSettingsFieldsAndOptionsRoute
  '/app/$workspaceSlug/$eventSlug/settings/integrations': typeof AppWorkspaceSlugEventSlugSettingsIntegrationsRoute
  '/app/$workspaceSlug/$eventSlug/settings/rooms-and-tracks': typeof AppWorkspaceSlugEventSlugSettingsRoomsAndTracksRoute
  '/app/$workspaceSlug/$eventSlug/settings/statuses': typeof AppWorkspaceSlugEventSlugSettingsStatusesRoute
  '/app/$workspaceSlug/$eventSlug/settings/team': typeof AppWorkspaceSlugEventSlugSettingsTeamRoute
  '/e/$workspaceSlug/$eventSlug/itinerary/$personId': typeof EWorkspaceSlugEventSlugItineraryPersonIdRoute
  '/e/$workspaceSlug/$eventSlug/sessions/$sessionId': typeof EWorkspaceSlugEventSlugSessionsSessionIdRoute
  '/app/$workspaceSlug/$eventSlug/agenda/': typeof AppWorkspaceSlugEventSlugAgendaIndexRoute
  '/app/$workspaceSlug/$eventSlug/communications/': typeof AppWorkspaceSlugEventSlugCommunicationsIndexRoute
  '/app/$workspaceSlug/$eventSlug/embeds/': typeof AppWorkspaceSlugEventSlugEmbedsIndexRoute
  '/app/$workspaceSlug/$eventSlug/evaluation/': typeof AppWorkspaceSlugEventSlugEvaluationIndexRoute
  '/app/$workspaceSlug/$eventSlug/files/': typeof AppWorkspaceSlugEventSlugFilesIndexRoute
  '/app/$workspaceSlug/$eventSlug/forms/': typeof AppWorkspaceSlugEventSlugFormsIndexRoute
  '/app/$workspaceSlug/$eventSlug/settings/': typeof AppWorkspaceSlugEventSlugSettingsIndexRoute
  '/app/$workspaceSlug/$eventSlug/speakers/': typeof AppWorkspaceSlugEventSlugSpeakersIndexRoute
  '/app/$workspaceSlug/$eventSlug/submissions/': typeof AppWorkspaceSlugEventSlugSubmissionsIndexRoute
  '/e/$workspaceSlug/$eventSlug/sessions/': typeof EWorkspaceSlugEventSlugSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/docs'
    | '/portal'
    | '/confirm-email'
    | '/design-system'
    | '/get'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/.well-known/oauth-authorization-server'
    | '/api/chat'
    | '/app/account'
    | '/app/copilot'
    | '/app/workspace'
    | '/docs/mcp'
    | '/docs/self-host'
    | '/docs/api'
    | '/portal/profile'
    | '/portal/submissions'
    | '/portal/tasks'
    | '/review/$token'
    | '/app/'
    | '/docs/'
    | '/portal/'
    | '/app/$workspaceSlug/$eventSlug'
    | '/e/$workspaceSlug/$eventSlug'
    | '/api/auth/$'
    | '/app/$workspaceSlug/workspace'
    | '/app/evaluation/$planId'
    | '/app/forms/$formId'
    | '/app/forms/new'
    | '/app/settings/activity'
    | '/app/settings/api-mcp'
    | '/app/settings/fields-and-options'
    | '/app/settings/integrations'
    | '/app/settings/rooms-and-tracks'
    | '/app/settings/statuses'
    | '/docs/guide/ai-copilot'
    | '/docs/guide/airtable-sync'
    | '/docs/guide/build-the-agenda'
    | '/docs/guide/chase-speakers'
    | '/docs/guide/create-a-cfp-form'
    | '/docs/guide/getting-started'
    | '/docs/guide/publish-your-program'
    | '/docs/guide/review-and-decide'
    | '/docs/guide/share-and-collect'
    | '/docs/guide/speaker-portal'
    | '/docs/guide/team-and-workspaces'
    | '/portal/t/$token'
    | '/app/$workspaceSlug/'
    | '/app/agenda/'
    | '/app/communications/'
    | '/app/embeds/'
    | '/app/evaluation/'
    | '/app/events/'
    | '/app/files/'
    | '/app/forms/'
    | '/app/settings/'
    | '/app/speakers/'
    | '/app/submissions/'
    | '/e/$workspaceSlug/'
    | '/submit/$workspaceSlug/'
    | '/app/$workspaceSlug/$eventSlug/settings'
    | '/e/$workspaceSlug/$eventSlug/$'
    | '/e/$workspaceSlug/$eventSlug/my-schedule'
    | '/e/$workspaceSlug/$eventSlug/speakers'
    | '/submit/$workspaceSlug/$eventSlug/$formSlug'
    | '/app/$workspaceSlug/$eventSlug/'
    | '/e/$workspaceSlug/$eventSlug/'
    | '/submit/$workspaceSlug/$eventSlug/'
    | '/app/$workspaceSlug/$eventSlug/evaluation/$planId'
    | '/app/$workspaceSlug/$eventSlug/forms/$formId'
    | '/app/$workspaceSlug/$eventSlug/forms/new'
    | '/app/$workspaceSlug/$eventSlug/settings/activity'
    | '/app/$workspaceSlug/$eventSlug/settings/api-mcp'
    | '/app/$workspaceSlug/$eventSlug/settings/fields-and-options'
    | '/app/$workspaceSlug/$eventSlug/settings/integrations'
    | '/app/$workspaceSlug/$eventSlug/settings/rooms-and-tracks'
    | '/app/$workspaceSlug/$eventSlug/settings/statuses'
    | '/app/$workspaceSlug/$eventSlug/settings/team'
    | '/e/$workspaceSlug/$eventSlug/itinerary/$personId'
    | '/e/$workspaceSlug/$eventSlug/sessions/$sessionId'
    | '/app/$workspaceSlug/$eventSlug/agenda/'
    | '/app/$workspaceSlug/$eventSlug/communications/'
    | '/app/$workspaceSlug/$eventSlug/embeds/'
    | '/app/$workspaceSlug/$eventSlug/evaluation/'
    | '/app/$workspaceSlug/$eventSlug/files/'
    | '/app/$workspaceSlug/$eventSlug/forms/'
    | '/app/$workspaceSlug/$eventSlug/settings/'
    | '/app/$workspaceSlug/$eventSlug/speakers/'
    | '/app/$workspaceSlug/$eventSlug/submissions/'
    | '/e/$workspaceSlug/$eventSlug/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm-email'
    | '/design-system'
    | '/get'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/.well-known/oauth-authorization-server'
    | '/api/chat'
    | '/app/account'
    | '/app/copilot'
    | '/app/workspace'
    | '/docs/mcp'
    | '/docs/self-host'
    | '/docs/api'
    | '/portal/profile'
    | '/portal/submissions'
    | '/portal/tasks'
    | '/review/$token'
    | '/app'
    | '/docs'
    | '/portal'
    | '/api/auth/$'
    | '/app/$workspaceSlug/workspace'
    | '/app/evaluation/$planId'
    | '/app/forms/$formId'
    | '/app/forms/new'
    | '/app/settings/activity'
    | '/app/settings/api-mcp'
    | '/app/settings/fields-and-options'
    | '/app/settings/integrations'
    | '/app/settings/rooms-and-tracks'
    | '/app/settings/statuses'
    | '/docs/guide/ai-copilot'
    | '/docs/guide/airtable-sync'
    | '/docs/guide/build-the-agenda'
    | '/docs/guide/chase-speakers'
    | '/docs/guide/create-a-cfp-form'
    | '/docs/guide/getting-started'
    | '/docs/guide/publish-your-program'
    | '/docs/guide/review-and-decide'
    | '/docs/guide/share-and-collect'
    | '/docs/guide/speaker-portal'
    | '/docs/guide/team-and-workspaces'
    | '/portal/t/$token'
    | '/app/$workspaceSlug'
    | '/app/agenda'
    | '/app/communications'
    | '/app/embeds'
    | '/app/evaluation'
    | '/app/events'
    | '/app/files'
    | '/app/forms'
    | '/app/settings'
    | '/app/speakers'
    | '/app/submissions'
    | '/e/$workspaceSlug'
    | '/submit/$workspaceSlug'
    | '/e/$workspaceSlug/$eventSlug/$'
    | '/e/$workspaceSlug/$eventSlug/my-schedule'
    | '/e/$workspaceSlug/$eventSlug/speakers'
    | '/submit/$workspaceSlug/$eventSlug/$formSlug'
    | '/app/$workspaceSlug/$eventSlug'
    | '/e/$workspaceSlug/$eventSlug'
    | '/submit/$workspaceSlug/$eventSlug'
    | '/app/$workspaceSlug/$eventSlug/evaluation/$planId'
    | '/app/$workspaceSlug/$eventSlug/forms/$formId'
    | '/app/$workspaceSlug/$eventSlug/forms/new'
    | '/app/$workspaceSlug/$eventSlug/settings/activity'
    | '/app/$workspaceSlug/$eventSlug/settings/api-mcp'
    | '/app/$workspaceSlug/$eventSlug/settings/fields-and-options'
    | '/app/$workspaceSlug/$eventSlug/settings/integrations'
    | '/app/$workspaceSlug/$eventSlug/settings/rooms-and-tracks'
    | '/app/$workspaceSlug/$eventSlug/settings/statuses'
    | '/app/$workspaceSlug/$eventSlug/settings/team'
    | '/e/$workspaceSlug/$eventSlug/itinerary/$personId'
    | '/e/$workspaceSlug/$eventSlug/sessions/$sessionId'
    | '/app/$workspaceSlug/$eventSlug/agenda'
    | '/app/$workspaceSlug/$eventSlug/communications'
    | '/app/$workspaceSlug/$eventSlug/embeds'
    | '/app/$workspaceSlug/$eventSlug/evaluation'
    | '/app/$workspaceSlug/$eventSlug/files'
    | '/app/$workspaceSlug/$eventSlug/forms'
    | '/app/$workspaceSlug/$eventSlug/settings'
    | '/app/$workspaceSlug/$eventSlug/speakers'
    | '/app/$workspaceSlug/$eventSlug/submissions'
    | '/e/$workspaceSlug/$eventSlug/sessions'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/docs'
    | '/portal'
    | '/confirm-email'
    | '/design-system'
    | '/get'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/.well-known/oauth-authorization-server'
    | '/api/chat'
    | '/app/account'
    | '/app/copilot'
    | '/app/workspace'
    | '/docs/mcp'
    | '/docs/self-host'
    | '/docs_/api'
    | '/portal/profile'
    | '/portal/submissions'
    | '/portal/tasks'
    | '/review/$token'
    | '/app/'
    | '/docs/'
    | '/portal/'
    | '/app/$workspaceSlug/$eventSlug'
    | '/e/$workspaceSlug/$eventSlug'
    | '/api/auth/$'
    | '/app/$workspaceSlug/workspace'
    | '/app/evaluation/$planId'
    | '/app/forms/$formId'
    | '/app/forms/new'
    | '/app/settings/activity'
    | '/app/settings/api-mcp'
    | '/app/settings/fields-and-options'
    | '/app/settings/integrations'
    | '/app/settings/rooms-and-tracks'
    | '/app/settings/statuses'
    | '/docs/guide/ai-copilot'
    | '/docs/guide/airtable-sync'
    | '/docs/guide/build-the-agenda'
    | '/docs/guide/chase-speakers'
    | '/docs/guide/create-a-cfp-form'
    | '/docs/guide/getting-started'
    | '/docs/guide/publish-your-program'
    | '/docs/guide/review-and-decide'
    | '/docs/guide/share-and-collect'
    | '/docs/guide/speaker-portal'
    | '/docs/guide/team-and-workspaces'
    | '/portal/t/$token'
    | '/app/$workspaceSlug/'
    | '/app/agenda/'
    | '/app/communications/'
    | '/app/embeds/'
    | '/app/evaluation/'
    | '/app/events/'
    | '/app/files/'
    | '/app/forms/'
    | '/app/settings/'
    | '/app/speakers/'
    | '/app/submissions/'
    | '/e/$workspaceSlug/'
    | '/submit/$workspaceSlug/'
    | '/app/$workspaceSlug/$eventSlug/settings'
    | '/e/$workspaceSlug/$eventSlug/$'
    | '/e/$workspaceSlug/$eventSlug/my-schedule'
    | '/e/$workspaceSlug/$eventSlug/speakers'
    | '/submit/$workspaceSlug/$eventSlug/$formSlug'
    | '/app/$workspaceSlug/$eventSlug/'
    | '/e/$workspaceSlug/$eventSlug/'
    | '/submit/$workspaceSlug/$eventSlug/'
    | '/app/$workspaceSlug/$eventSlug/evaluation/$planId'
    | '/app/$workspaceSlug/$eventSlug/forms/$formId'
    | '/app/$workspaceSlug/$eventSlug/forms/new'
    | '/app/$workspaceSlug/$eventSlug/settings/activity'
    | '/app/$workspaceSlug/$eventSlug/settings/api-mcp'
    | '/app/$workspaceSlug/$eventSlug/settings/fields-and-options'
    | '/app/$workspaceSlug/$eventSlug/settings/integrations'
    | '/app/$workspaceSlug/$eventSlug/settings/rooms-and-tracks'
    | '/app/$workspaceSlug/$eventSlug/settings/statuses'
    | '/app/$workspaceSlug/$eventSlug/settings/team'
    | '/e/$workspaceSlug/$eventSlug/itinerary/$personId'
    | '/e/$workspaceSlug/$eventSlug/sessions/$sessionId'
    | '/app/$workspaceSlug/$eventSlug/agenda/'
    | '/app/$workspaceSlug/$eventSlug/communications/'
    | '/app/$workspaceSlug/$eventSlug/embeds/'
    | '/app/$workspaceSlug/$eventSlug/evaluation/'
    | '/app/$workspaceSlug/$eventSlug/files/'
    | '/app/$workspaceSlug/$eventSlug/forms/'
    | '/app/$workspaceSlug/$eventSlug/settings/'
    | '/app/$workspaceSlug/$eventSlug/speakers/'
    | '/app/$workspaceSlug/$eventSlug/submissions/'
    | '/e/$workspaceSlug/$eventSlug/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  DesignSystemRoute: typeof DesignSystemRoute
  GetRoute: typeof GetRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  ApiChatRoute: typeof ApiChatRoute
  DocsApiRoute: typeof DocsApiRoute
  ReviewTokenRoute: typeof ReviewTokenRoute
  EWorkspaceSlugEventSlugRouteRoute: typeof EWorkspaceSlugEventSlugRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  EWorkspaceSlugIndexRoute: typeof EWorkspaceSlugIndexRoute
  SubmitWorkspaceSlugIndexRoute: typeof SubmitWorkspaceSlugIndexRoute
  SubmitWorkspaceSlugEventSlugFormSlugRoute: typeof SubmitWorkspaceSlugEventSlugFormSlugRoute
  SubmitWorkspaceSlugEventSlugIndexRoute: typeof SubmitWorkspaceSlugEventSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get': {
      id: '/get'
      path: '/get'
      fullPath: '/get'
      preLoaderRoute: typeof GetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/copilot': {
      id: '/app/copilot'
      path: '/copilot'
      fullPath: '/app/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/workspace': {
      id: '/app/workspace'
      path: '/workspace'
      fullPath: '/app/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/mcp': {
      id: '/docs/mcp'
      path: '/mcp'
      fullPath: '/docs/mcp'
      preLoaderRoute: typeof DocsMcpRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/self-host': {
      id: '/docs/self-host'
      path: '/self-host'
      fullPath: '/docs/self-host'
      preLoaderRoute: typeof DocsSelfHostRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs_/api': {
      id: '/docs_/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/submissions': {
      id: '/portal/submissions'
      path: '/submissions'
      fullPath: '/portal/submissions'
      preLoaderRoute: typeof PortalSubmissionsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/tasks': {
      id: '/portal/tasks'
      path: '/tasks'
      fullPath: '/portal/tasks'
      preLoaderRoute: typeof PortalTasksRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/review/$token': {
      id: '/review/$token'
      path: '/review/$token'
      fullPath: '/review/$token'
      preLoaderRoute: typeof ReviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$workspaceSlug/': {
      id: '/app/$workspaceSlug/'
      path: '/$workspaceSlug'
      fullPath: '/app/$workspaceSlug/'
      preLoaderRoute: typeof AppWorkspaceSlugIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$workspaceSlug/$eventSlug': {
      id: '/app/$workspaceSlug/$eventSlug'
      path: '/$workspaceSlug/$eventSlug'
      fullPath: '/app/$workspaceSlug/$eventSlug'
      preLoaderRoute: typeof AppWorkspaceSlugEventSlugRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$workspaceSlug/workspace': {
      id: '/app/$workspaceSlug/workspace'
      path: '/$workspaceSlug/workspace'
      fullPath: '/app/$workspaceSlug/workspace'
      preLoaderRoute: typeof AppWorkspaceSlugWorkspaceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/agenda/': {
      id: '/app/agenda/'
      path: '/agenda'
      fullPath: '/app/agenda/'
      preLoaderRoute: typeof AppAgendaIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/communications/': {
      id: '/app/communications/'
      path: '/communications'
      fullPath: '/app/communications/'
      preLoaderRoute: typeof AppCommunicationsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/embeds/': {
      id: '/app/embeds/'
      path: '/embeds'
      fullPath: '/app/embeds/'
      preLoaderRoute: typeof AppEmbedsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/evaluation/': {
      id: '/app/evaluation/'
      path: '/evaluation'
      fullPath: '/app/evaluation/'
      preLoaderRoute: typeof AppEvaluationIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/evaluation/$planId': {
      id: '/app/evaluation/$planId'
      path: '/evaluation/$planId'
      fullPath: '/app/evaluation/$planId'
      preLoaderRoute: typeof AppEvaluationPlanIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/events/': {
      id: '/app/events/'
      path: '/events'
      fullPath: '/app/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/files/': {
      id: '/app/files/'
      path: '/files'
      fullPath: '/app/files/'
      preLoaderRoute: typeof AppFilesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/forms/': {
      id: '/app/forms/'
      path: '/forms'
      fullPath: '/app/forms/'
      preLoaderRoute: typeof AppFormsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/forms/$formId': {
      id: '/app/forms/$formId'
      path: '/forms/$formId'
      fullPath: '/app/forms/$formId'
      preLoaderRoute: typeof AppFormsFormIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/forms/new': {
      id: '/app/forms/new'
      path: '/forms/new'
      fullPath: '/app/forms/new'
      preLoaderRoute: typeof AppFormsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/activity': {
      id: '/app/settings/activity'
      path: '/settings/activity'
      fullPath: '/app/settings/activity'
      preLoaderRoute: typeof AppSettingsActivityRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/api-mcp': {
      id: '/app/settings/api-mcp'
      path: '/settings/api-mcp'
      fullPath: '/app/settings/api-mcp'
      preLoaderRoute: typeof AppSettingsApiMcpRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/fields-and-options': {
      id: '/app/settings/fields-and-options'
      path: '/settings/fields-and-options'
      fullPath: '/app/settings/fields-and-options'
      preLoaderRoute: typeof AppSettingsFieldsAndOptionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/integrations': {
      id: '/app/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/app/settings/integrations'
      preLoaderRoute: typeof AppSettingsIntegrationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/rooms-and-tracks': {
      id: '/app/settings/rooms-and-tracks'
      path: '/settings/rooms-and-tracks'
      fullPath: '/app/settings/rooms-and-tracks'
      preLoaderRoute: typeof AppSettingsRoomsAndTracksRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/statuses': {
      id: '/app/settings/statuses'
      path: '/settings/statuses'
      fullPath: '/app/settings/statuses'
      preLoaderRoute: typeof AppSettingsStatusesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/speakers/': {
      id: '/app/speakers/'
      path: '/speakers'
      fullPath: '/app/speakers/'
      preLoaderRoute: typeof AppSpeakersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/submissions/': {
      id: '/app/submissions/'
      path: '/submissions'
      fullPath: '/app/submissions/'
      preLoaderRoute: typeof AppSubmissionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/docs/guide/ai-copilot': {
      id: '/docs/guide/ai-copilot'
      path: '/guide/ai-copilot'
      fullPath: '/docs/guide/ai-copilot'
      preLoaderRoute: typeof DocsGuideAiCopilotRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/guide/airtable-sync': {
      id: '/docs/guide/airtable-sync'
      path: '/guide/airtable-sync'
      fullPath: '/docs/guide/airtable-sync'
      preLoaderRoute: typeof DocsGuideAirtableSyncRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/guide/build-the-agenda': {
      id: '/docs/guide/build-the-agenda'
      path: '/guide/build-the-agenda'
      fullPath: '/docs/guide/build-the-agenda'
      preLoaderRoute: typeof DocsGuideBuildTheAgendaRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/guide/chase-speakers': {
      id: '/docs/guide/chase-speakers'
      path: '/guide/chase-speakers'
      fullPath: '/docs/guide/chase-speakers'
      preLoaderRoute: typeof DocsGuideChaseSpeakersRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/guide/create-a-cfp-form': {
      id: '/docs/guide/create-a-cfp-form'
      path: '/guide/create-a-cfp-form'
      fullPath: '/docs/guide/create-a-cfp-form'
      preLoaderRoute: typeof DocsGuideCreateACfpFormRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/guide/getting-started': {
      id: '/docs/guide/getting-started'
      path: '/guide/getting-started'
      fullPath: '/docs/guide/getting-started'
      preLoaderRoute: typeof DocsGuideGettingStartedRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/guide/publish-your-program': {
      id: '/docs/guide/publish-your-program'
      path: '/guide/publish-your-program'
      fullPath: '/docs/guide/publish-your-program'
      preLoaderRoute: typeof DocsGuidePublishYourProgramRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/guide/review-and-decide': {
      id: '/docs/guide/review-and-decide'
      path: '/guide/review-and-decide'
      fullPath: '/docs/guide/review-and-decide'
      preLoaderRoute: typeof DocsGuideReviewAndDecideRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/guide/share-and-collect': {
      id: '/docs/guide/share-and-collect'
      path: '/guide/share-and-collect'
      fullPath: '/docs/guide/share-and-collect'
      preLoaderRoute: typeof DocsGuideShareAndCollectRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/guide/speaker-portal': {
      id: '/docs/guide/speaker-portal'
      path: '/guide/speaker-portal'
      fullPath: '/docs/guide/speaker-portal'
      preLoaderRoute: typeof DocsGuideSpeakerPortalRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/guide/team-and-workspaces': {
      id: '/docs/guide/team-and-workspaces'
      path: '/guide/team-and-workspaces'
      fullPath: '/docs/guide/team-and-workspaces'
      preLoaderRoute: typeof DocsGuideTeamAndWorkspacesRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/e/$workspaceSlug/': {
      id: '/e/$workspaceSlug/'
      path: '/e/$workspaceSlug'
      fullPath: '/e/$workspaceSlug/'
      preLoaderRoute: typeof EWorkspaceSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$workspaceSlug/$eventSlug': {
      id: '/e/$workspaceSlug/$eventSlug'
      path: '/e/$workspaceSlug/$eventSlug'
      fullPath: '/e/$workspaceSlug/$eventSlug'
      preLoaderRoute: typeof EWorkspaceSlugEventSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/t/$token': {
      id: '/portal/t/$token'
      path: '/t/$token'
      fullPath: '/portal/t/$token'
      preLoaderRoute: typeof PortalTTokenRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/submit/$workspaceSlug/': {
      id: '/submit/$workspaceSlug/'
      path: '/submit/$workspaceSlug'
      fullPath: '/submit/$workspaceSlug/'
      preLoaderRoute: typeof SubmitWorkspaceSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$workspaceSlug/$eventSlug/': {
      id: '/app/$workspaceSlug/$eventSlug/'
      path: '/'
      fullPath: '/app/$workspaceSlug/$eventSlug/'
      preLoaderRoute: typeof AppWorkspaceSlugEventSlugIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugEventSlugRouteRoute
    }
    '/app/$workspaceSlug/$eventSlug/settings': {
      id: '/app/$workspaceSlug/$eventSlug/settings'
      path: '/settings'
      fullPath: '/app/$workspaceSlug/$eventSlug/settings'
      preLoaderRoute: typeof AppWorkspaceSlugEventSlugSettingsRouteRouteImport
      parentRoute: typeof AppWorkspaceSlugEventSlugRouteRoute
    }
    '/e/$workspaceSlug/$eventSlug/': {
      id: '/e/$workspaceSlug/$eventSlug/'
      path: '/'
      fullPath: '/e/$workspaceSlug/$eventSlug/'
      preLoaderRoute: typeof EWorkspaceSlugEventSlugIndexRouteImport
      parentRoute: typeof EWorkspaceSlugEventSlugRouteRoute
    }
    '/e/$workspaceSlug/$eventSlug/$': {
      id: '/e/$workspaceSlug/$eventSlug/$'
      path: '/$'
      fullPath: '/e/$workspaceSlug/$eventSlug/$'
      preLoaderRoute: typeof EWorkspaceSlugEventSlugSplatRouteImport
      parentRoute: typeof EWorkspaceSlugEventSlugRouteRoute
    }
    '/e/$workspaceSlug/$eventSlug/my-schedule': {
      id: '/e/$workspaceSlug/$eventSlug/my-schedule'
      path: '/my-schedule'
      fullPath: '/e/$workspaceSlug/$eventSlug/my-schedule'
      preLoaderRoute: typeof EWorkspaceSlugEventSlugMyScheduleRouteImport
      parentRoute: typeof EWorkspaceSlugEventSlugRouteRoute
    }
    '/e/$workspaceSlug/$eventSlug/speakers': {
      id: '/e/$workspaceSlug/$eventSlug/speakers'
      path: '/speakers'
      fullPath: '/e/$workspaceSlug/$eventSlug/speakers'
      preLoaderRoute: typeof EWorkspaceSlugEventSlugSpeakersRouteImport
      parentRoute: typeof EWorkspaceSlugEventSlugRouteRoute
    }
    '/submit/$workspaceSlug/$eventSlug/': {
      id: '/submit/$workspaceSlug/$eventSlug/'
      path: '/submit/$workspaceSlug/$eventSlug'
      fullPath: '/submit/$workspaceSlug/$eventSlug/'
      preLoaderRoute: typeof SubmitWorkspaceSlugEventSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit/$workspaceSlug/$eventSlug/$formSlug': {
      id: '/submit/$workspaceSlug/$eventSlug/$formSlug'
      path: '/submit/$workspaceSlug/$eventSlug/$formSlug'
      fullPath: '/submit/$workspaceSlug/$eventSlug/$formSlug'
      preLoaderRoute: typeof SubmitWorkspaceSlugEventSlugFormSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$workspaceSlug/$eventSlug/agenda/': {
      id: '/app/$workspaceSlug/$eventSlug/agenda/'
      path: '/agenda'
      fullPath: '/app/$workspaceSlug/$eventSlug/agenda/'
      preLoaderRoute: typeof AppWorkspaceSlugEventSlugAgendaIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugEventSlugRouteRoute
    }
    '/app/$workspaceSlug/$eventSlug/communications/': {
      id: '/app/$workspaceSlug/$eventSlug/communications/'
      path: '/communications'
      fullPath: '/app/$workspaceSlug/$eventSlug/communications/'
      preLoaderRoute: typeof AppWorkspaceSlugEventSlugCommunicationsIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugEventSlugRouteRoute
    }
    '/app/$workspaceSlug/$eventSlug/embeds/': {
      id: '/app/$workspaceSlug/$eventSlug/embeds/'
      path: '/embeds'
      fullPath: '/app/$workspaceSlug/$eventSlug/embeds/'
      preLoaderRoute: typeof AppWorkspaceSlugEventSlugEmbedsIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugEventSlugRouteRoute
    }
    '/app/$workspaceSlug/$eventSlug/evaluation/': {
      id: '/app/$workspaceSlug/$eventSlug/evaluation/'
      path: '/evaluation'
      fullPath: '/app/$workspaceSlug/$eventSlug/evaluation/'
      preLoaderRoute: typeof AppWorkspaceSlugEventSlugEvaluationIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugEventSlugRouteRoute
    }
    '/app/$workspaceSlug/$eventSlug/evaluation/$planId': {
      id: '/app/$workspaceSlug/$eventSlug/evaluation/$planId'
      path: '/evaluation/$planId'
      fullPath: '/app/$workspaceSlug/$eventSlug/evaluation/$planId'
      preLoaderRoute: typeof AppWorkspaceSlugEventSlugEvaluationPlanIdRouteImport
      parentRoute: typeof AppWorkspaceSlugEventSlugRouteRoute
    }
    '/app/$workspaceSlug/$eventSlug/files/': {
      id: '/app/$workspaceSlug/$eventSlug/files/'
      path: '/files'
      fullPath: '/app/$workspaceSlug/$eventSlug/files/'
      preLoaderRoute: typeof AppWorkspaceSlugEventSlugFilesIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugEventSlugRouteRoute
    }
    '/app/$workspaceSlug/$eventSlug/forms/': {
      id: '/app/$workspaceSlug/$eventSlug/forms/'
      path: '/forms'
      fullPath: '/app/$workspaceSlug/$eventSlug/forms/'
      preLoaderRoute: typeof AppWorkspaceSlugEventSlugFormsIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugEventSlugRouteRoute
    }
    '/app/$workspaceSlug/$eventSlug/forms/$formId': {
      id: '/app/$workspaceSlug/$eventSlug/forms/$formId'
      path: '/forms/$formId'
      fullPath: '/app/$workspaceSlug/$eventSlug/forms/$formId'
      preLoaderRoute: typeof AppWorkspaceSlugEventSlugFormsFormIdRouteImport
      parentRoute: typeof AppWorkspaceSlugEventSlugRouteRoute
    }
    '/app/$workspaceSlug/$eventSlug/forms/new': {
      id: '/app/$workspaceSlug/$eventSlug/forms/new'
      path: '/forms/new'
      fullPath: '/app/$workspaceSlug/$eventSlug/forms/new'
      preLoaderRoute: typeof AppWorkspaceSlugEventSlugFormsNewRouteImport
      parentRoute: typeof AppWorkspaceSlugEventSlugRouteRoute
    }
    '/app/$workspaceSlug/$eventSlug/settings/': {
      id: '/app/$workspaceSlug/$eventSlug/settings/'
      path: '/'
      fullPath: '/app/$workspaceSlug/$eventSlug/settings/'
      preLoaderRoute: typeof AppWorkspaceSlugEventSlugSettingsIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugEventSlugSettingsRouteRoute
    }
    '/app/$workspaceSlug/$eventSlug/settings/activity': {
      id: '/app/$workspaceSlug/$eventSlug/settings/activity'
      path: '/activity'
      fullPath: '/app/$workspaceSlug/$eventSlug/settings/activity'
      preLoaderRoute: typeof AppWorkspaceSlugEventSlugSettingsActivityRouteImport
      parentRoute: typeof AppWorkspaceSlugEventSlugSettingsRouteRoute
    }
    '/app/$workspaceSlug/$eventSlug/settings/api-mcp': {
      id: '/app/$workspaceSlug/$eventSlug/settings/api-mcp'
      path: '/api-mcp'
      fullPath: '/app/$workspaceSlug/$eventSlug/settings/api-mcp'
      preLoaderRoute: typeof AppWorkspaceSlugEventSlugSettingsApiMcpRouteImport
      parentRoute: typeof AppWorkspaceSlugEventSlugSettingsRouteRoute
    }
    '/app/$workspaceSlug/$eventSlug/settings/fields-and-options': {
      id: '/app/$workspaceSlug/$eventSlug/settings/fields-and-options'
      path: '/fields-and-options'
      fullPath: '/app/$workspaceSlug/$eventSlug/settings/fields-and-options'
      preLoaderRoute: typeof AppWorkspaceSlugEventSlugSettingsFieldsAndOptionsRouteImport
      parentRoute: typeof AppWorkspaceSlugEventSlugSettingsRouteRoute
    }
    '/app/$workspaceSlug/$eventSlug/settings/integrations': {
      id: '/app/$workspaceSlug/$eventSlug/settings/integrations'
      path: '/integrations'
      fullPath: '/app/$workspaceSlug/$eventSlug/settings/integrations'
      preLoaderRoute: typeof AppWorkspaceSlugEventSlugSettingsIntegrationsRouteImport
      parentRoute: typeof AppWorkspaceSlugEventSlugSettingsRouteRoute
    }
    '/app/$workspaceSlug/$eventSlug/settings/rooms-and-tracks': {
      id: '/app/$workspaceSlug/$eventSlug/settings/rooms-and-tracks'
      path: '/rooms-and-tracks'
      fullPath: '/app/$workspaceSlug/$eventSlug/settings/rooms-and-tracks'
      preLoaderRoute: typeof AppWorkspaceSlugEventSlugSettingsRoomsAndTracksRouteImport
      parentRoute: typeof AppWorkspaceSlugEventSlugSettingsRouteRoute
    }
    '/app/$workspaceSlug/$eventSlug/settings/statuses': {
      id: '/app/$workspaceSlug/$eventSlug/settings/statuses'
      path: '/statuses'
      fullPath: '/app/$workspaceSlug/$eventSlug/settings/statuses'
      preLoaderRoute: typeof AppWorkspaceSlugEventSlugSettingsStatusesRouteImport
      parentRoute: typeof AppWorkspaceSlugEventSlugSettingsRouteRoute
    }
    '/app/$workspaceSlug/$eventSlug/settings/team': {
      id: '/app/$workspaceSlug/$eventSlug/settings/team'
      path: '/team'
      fullPath: '/app/$workspaceSlug/$eventSlug/settings/team'
      preLoaderRoute: typeof AppWorkspaceSlugEventSlugSettingsTeamRouteImport
      parentRoute: typeof AppWorkspaceSlugEventSlugSettingsRouteRoute
    }
    '/app/$workspaceSlug/$eventSlug/speakers/': {
      id: '/app/$workspaceSlug/$eventSlug/speakers/'
      path: '/speakers'
      fullPath: '/app/$workspaceSlug/$eventSlug/speakers/'
      preLoaderRoute: typeof AppWorkspaceSlugEventSlugSpeakersIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugEventSlugRouteRoute
    }
    '/app/$workspaceSlug/$eventSlug/submissions/': {
      id: '/app/$workspaceSlug/$eventSlug/submissions/'
      path: '/submissions'
      fullPath: '/app/$workspaceSlug/$eventSlug/submissions/'
      preLoaderRoute: typeof AppWorkspaceSlugEventSlugSubmissionsIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugEventSlugRouteRoute
    }
    '/e/$workspaceSlug/$eventSlug/itinerary/$personId': {
      id: '/e/$workspaceSlug/$eventSlug/itinerary/$personId'
      path: '/itinerary/$personId'
      fullPath: '/e/$workspaceSlug/$eventSlug/itinerary/$personId'
      preLoaderRoute: typeof EWorkspaceSlugEventSlugItineraryPersonIdRouteImport
      parentRoute: typeof EWorkspaceSlugEventSlugRouteRoute
    }
    '/e/$workspaceSlug/$eventSlug/sessions/': {
      id: '/e/$workspaceSlug/$eventSlug/sessions/'
      path: '/sessions'
      fullPath: '/e/$workspaceSlug/$eventSlug/sessions/'
      preLoaderRoute: typeof EWorkspaceSlugEventSlugSessionsIndexRouteImport
      parentRoute: typeof EWorkspaceSlugEventSlugRouteRoute
    }
    '/e/$workspaceSlug/$eventSlug/sessions/$sessionId': {
      id: '/e/$workspaceSlug/$eventSlug/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/e/$workspaceSlug/$eventSlug/sessions/$sessionId'
      preLoaderRoute: typeof EWorkspaceSlugEventSlugSessionsSessionIdRouteImport
      parentRoute: typeof EWorkspaceSlugEventSlugRouteRoute
    }
  }
}

interface AppWorkspaceSlugEventSlugSettingsRouteRouteChildren {
  AppWorkspaceSlugEventSlugSettingsActivityRoute: typeof AppWorkspaceSlugEventSlugSettingsActivityRoute
  AppWorkspaceSlugEventSlugSettingsApiMcpRoute: typeof AppWorkspaceSlugEventSlugSettingsApiMcpRoute
  AppWorkspaceSlugEventSlugSettingsFieldsAndOptionsRoute: typeof AppWorkspaceSlugEventSlugSettingsFieldsAndOptionsRoute
  AppWorkspaceSlugEventSlugSettingsIntegrationsRoute: typeof AppWorkspaceSlugEventSlugSettingsIntegrationsRoute
  AppWorkspaceSlugEventSlugSettingsRoomsAndTracksRoute: typeof AppWorkspaceSlugEventSlugSettingsRoomsAndTracksRoute
  AppWorkspaceSlugEventSlugSettingsStatusesRoute: typeof AppWorkspaceSlugEventSlugSettingsStatusesRoute
  AppWorkspaceSlugEventSlugSettingsTeamRoute: typeof AppWorkspaceSlugEventSlugSettingsTeamRoute
  AppWorkspaceSlugEventSlugSettingsIndexRoute: typeof AppWorkspaceSlugEventSlugSettingsIndexRoute
}

const AppWorkspaceSlugEventSlugSettingsRouteRouteChildren: AppWorkspaceSlugEventSlugSettingsRouteRouteChildren =
  {
    AppWorkspaceSlugEventSlugSettingsActivityRoute:
      AppWorkspaceSlugEventSlugSettingsActivityRoute,
    AppWorkspaceSlugEventSlugSettingsApiMcpRoute:
      AppWorkspaceSlugEventSlugSettingsApiMcpRoute,
    AppWorkspaceSlugEventSlugSettingsFieldsAndOptionsRoute:
      AppWorkspaceSlugEventSlugSettingsFieldsAndOptionsRoute,
    AppWorkspaceSlugEventSlugSettingsIntegrationsRoute:
      AppWorkspaceSlugEventSlugSettingsIntegrationsRoute,
    AppWorkspaceSlugEventSlugSettingsRoomsAndTracksRoute:
      AppWorkspaceSlugEventSlugSettingsRoomsAndTracksRoute,
    AppWorkspaceSlugEventSlugSettingsStatusesRoute:
      AppWorkspaceSlugEventSlugSettingsStatusesRoute,
    AppWorkspaceSlugEventSlugSettingsTeamRoute:
      AppWorkspaceSlugEventSlugSettingsTeamRoute,
    AppWorkspaceSlugEventSlugSettingsIndexRoute:
      AppWorkspaceSlugEventSlugSettingsIndexRoute,
  }

const AppWorkspaceSlugEventSlugSettingsRouteRouteWithChildren =
  AppWorkspaceSlugEventSlugSettingsRouteRoute._addFileChildren(
    AppWorkspaceSlugEventSlugSettingsRouteRouteChildren,
  )

interface AppWorkspaceSlugEventSlugRouteRouteChildren {
  AppWorkspaceSlugEventSlugSettingsRouteRoute: typeof AppWorkspaceSlugEventSlugSettingsRouteRouteWithChildren
  AppWorkspaceSlugEventSlugIndexRoute: typeof AppWorkspaceSlugEventSlugIndexRoute
  AppWorkspaceSlugEventSlugEvaluationPlanIdRoute: typeof AppWorkspaceSlugEventSlugEvaluationPlanIdRoute
  AppWorkspaceSlugEventSlugFormsFormIdRoute: typeof AppWorkspaceSlugEventSlugFormsFormIdRoute
  AppWorkspaceSlugEventSlugFormsNewRoute: typeof AppWorkspaceSlugEventSlugFormsNewRoute
  AppWorkspaceSlugEventSlugAgendaIndexRoute: typeof AppWorkspaceSlugEventSlugAgendaIndexRoute
  AppWorkspaceSlugEventSlugCommunicationsIndexRoute: typeof AppWorkspaceSlugEventSlugCommunicationsIndexRoute
  AppWorkspaceSlugEventSlugEmbedsIndexRoute: typeof AppWorkspaceSlugEventSlugEmbedsIndexRoute
  AppWorkspaceSlugEventSlugEvaluationIndexRoute: typeof AppWorkspaceSlugEventSlugEvaluationIndexRoute
  AppWorkspaceSlugEventSlugFilesIndexRoute: typeof AppWorkspaceSlugEventSlugFilesIndexRoute
  AppWorkspaceSlugEventSlugFormsIndexRoute: typeof AppWorkspaceSlugEventSlugFormsIndexRoute
  AppWorkspaceSlugEventSlugSpeakersIndexRoute: typeof AppWorkspaceSlugEventSlugSpeakersIndexRoute
  AppWorkspaceSlugEventSlugSubmissionsIndexRoute: typeof AppWorkspaceSlugEventSlugSubmissionsIndexRoute
}

const AppWorkspaceSlugEventSlugRouteRouteChildren: AppWorkspaceSlugEventSlugRouteRouteChildren =
  {
    AppWorkspaceSlugEventSlugSettingsRouteRoute:
      AppWorkspaceSlugEventSlugSettingsRouteRouteWithChildren,
    AppWorkspaceSlugEventSlugIndexRoute: AppWorkspaceSlugEventSlugIndexRoute,
    AppWorkspaceSlugEventSlugEvaluationPlanIdRoute:
      AppWorkspaceSlugEventSlugEvaluationPlanIdRoute,
    AppWorkspaceSlugEventSlugFormsFormIdRoute:
      AppWorkspaceSlugEventSlugFormsFormIdRoute,
    AppWorkspaceSlugEventSlugFormsNewRoute:
      AppWorkspaceSlugEventSlugFormsNewRoute,
    AppWorkspaceSlugEventSlugAgendaIndexRoute:
      AppWorkspaceSlugEventSlugAgendaIndexRoute,
    AppWorkspaceSlugEventSlugCommunicationsIndexRoute:
      AppWorkspaceSlugEventSlugCommunicationsIndexRoute,
    AppWorkspaceSlugEventSlugEmbedsIndexRoute:
      AppWorkspaceSlugEventSlugEmbedsIndexRoute,
    AppWorkspaceSlugEventSlugEvaluationIndexRoute:
      AppWorkspaceSlugEventSlugEvaluationIndexRoute,
    AppWorkspaceSlugEventSlugFilesIndexRoute:
      AppWorkspaceSlugEventSlugFilesIndexRoute,
    AppWorkspaceSlugEventSlugFormsIndexRoute:
      AppWorkspaceSlugEventSlugFormsIndexRoute,
    AppWorkspaceSlugEventSlugSpeakersIndexRoute:
      AppWorkspaceSlugEventSlugSpeakersIndexRoute,
    AppWorkspaceSlugEventSlugSubmissionsIndexRoute:
      AppWorkspaceSlugEventSlugSubmissionsIndexRoute,
  }

const AppWorkspaceSlugEventSlugRouteRouteWithChildren =
  AppWorkspaceSlugEventSlugRouteRoute._addFileChildren(
    AppWorkspaceSlugEventSlugRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppCopilotRoute: typeof AppCopilotRoute
  AppWorkspaceRoute: typeof AppWorkspaceRoute
  AppIndexRoute: typeof AppIndexRoute
  AppWorkspaceSlugEventSlugRouteRoute: typeof AppWorkspaceSlugEventSlugRouteRouteWithChildren
  AppWorkspaceSlugWorkspaceRoute: typeof AppWorkspaceSlugWorkspaceRoute
  AppEvaluationPlanIdRoute: typeof AppEvaluationPlanIdRoute
  AppFormsFormIdRoute: typeof AppFormsFormIdRoute
  AppFormsNewRoute: typeof AppFormsNewRoute
  AppSettingsActivityRoute: typeof AppSettingsActivityRoute
  AppSettingsApiMcpRoute: typeof AppSettingsApiMcpRoute
  AppSettingsFieldsAndOptionsRoute: typeof AppSettingsFieldsAndOptionsRoute
  AppSettingsIntegrationsRoute: typeof AppSettingsIntegrationsRoute
  AppSettingsRoomsAndTracksRoute: typeof AppSettingsRoomsAndTracksRoute
  AppSettingsStatusesRoute: typeof AppSettingsStatusesRoute
  AppWorkspaceSlugIndexRoute: typeof AppWorkspaceSlugIndexRoute
  AppAgendaIndexRoute: typeof AppAgendaIndexRoute
  AppCommunicationsIndexRoute: typeof AppCommunicationsIndexRoute
  AppEmbedsIndexRoute: typeof AppEmbedsIndexRoute
  AppEvaluationIndexRoute: typeof AppEvaluationIndexRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppFilesIndexRoute: typeof AppFilesIndexRoute
  AppFormsIndexRoute: typeof AppFormsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSpeakersIndexRoute: typeof AppSpeakersIndexRoute
  AppSubmissionsIndexRoute: typeof AppSubmissionsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppCopilotRoute: AppCopilotRoute,
  AppWorkspaceRoute: AppWorkspaceRoute,
  AppIndexRoute: AppIndexRoute,
  AppWorkspaceSlugEventSlugRouteRoute:
    AppWorkspaceSlugEventSlugRouteRouteWithChildren,
  AppWorkspaceSlugWorkspaceRoute: AppWorkspaceSlugWorkspaceRoute,
  AppEvaluationPlanIdRoute: AppEvaluationPlanIdRoute,
  AppFormsFormIdRoute: AppFormsFormIdRoute,
  AppFormsNewRoute: AppFormsNewRoute,
  AppSettingsActivityRoute: AppSettingsActivityRoute,
  AppSettingsApiMcpRoute: AppSettingsApiMcpRoute,
  AppSettingsFieldsAndOptionsRoute: AppSettingsFieldsAndOptionsRoute,
  AppSettingsIntegrationsRoute: AppSettingsIntegrationsRoute,
  AppSettingsRoomsAndTracksRoute: AppSettingsRoomsAndTracksRoute,
  AppSettingsStatusesRoute: AppSettingsStatusesRoute,
  AppWorkspaceSlugIndexRoute: AppWorkspaceSlugIndexRoute,
  AppAgendaIndexRoute: AppAgendaIndexRoute,
  AppCommunicationsIndexRoute: AppCommunicationsIndexRoute,
  AppEmbedsIndexRoute: AppEmbedsIndexRoute,
  AppEvaluationIndexRoute: AppEvaluationIndexRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppFilesIndexRoute: AppFilesIndexRoute,
  AppFormsIndexRoute: AppFormsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSpeakersIndexRoute: AppSpeakersIndexRoute,
  AppSubmissionsIndexRoute: AppSubmissionsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface DocsRouteRouteChildren {
  DocsMcpRoute: typeof DocsMcpRoute
  DocsSelfHostRoute: typeof DocsSelfHostRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsGuideAiCopilotRoute: typeof DocsGuideAiCopilotRoute
  DocsGuideAirtableSyncRoute: typeof DocsGuideAirtableSyncRoute
  DocsGuideBuildTheAgendaRoute: typeof DocsGuideBuildTheAgendaRoute
  DocsGuideChaseSpeakersRoute: typeof DocsGuideChaseSpeakersRoute
  DocsGuideCreateACfpFormRoute: typeof DocsGuideCreateACfpFormRoute
  DocsGuideGettingStartedRoute: typeof DocsGuideGettingStartedRoute
  DocsGuidePublishYourProgramRoute: typeof DocsGuidePublishYourProgramRoute
  DocsGuideReviewAndDecideRoute: typeof DocsGuideReviewAndDecideRoute
  DocsGuideShareAndCollectRoute: typeof DocsGuideShareAndCollectRoute
  DocsGuideSpeakerPortalRoute: typeof DocsGuideSpeakerPortalRoute
  DocsGuideTeamAndWorkspacesRoute: typeof DocsGuideTeamAndWorkspacesRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsMcpRoute: DocsMcpRoute,
  DocsSelfHostRoute: DocsSelfHostRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsGuideAiCopilotRoute: DocsGuideAiCopilotRoute,
  DocsGuideAirtableSyncRoute: DocsGuideAirtableSyncRoute,
  DocsGuideBuildTheAgendaRoute: DocsGuideBuildTheAgendaRoute,
  DocsGuideChaseSpeakersRoute: DocsGuideChaseSpeakersRoute,
  DocsGuideCreateACfpFormRoute: DocsGuideCreateACfpFormRoute,
  DocsGuideGettingStartedRoute: DocsGuideGettingStartedRoute,
  DocsGuidePublishYourProgramRoute: DocsGuidePublishYourProgramRoute,
  DocsGuideReviewAndDecideRoute: DocsGuideReviewAndDecideRoute,
  DocsGuideShareAndCollectRoute: DocsGuideShareAndCollectRoute,
  DocsGuideSpeakerPortalRoute: DocsGuideSpeakerPortalRoute,
  DocsGuideTeamAndWorkspacesRoute: DocsGuideTeamAndWorkspacesRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

interface PortalRouteRouteChildren {
  PortalProfileRoute: typeof PortalProfileRoute
  PortalSubmissionsRoute: typeof PortalSubmissionsRoute
  PortalTasksRoute: typeof PortalTasksRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalTTokenRoute: typeof PortalTTokenRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalProfileRoute: PortalProfileRoute,
  PortalSubmissionsRoute: PortalSubmissionsRoute,
  PortalTasksRoute: PortalTasksRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalTTokenRoute: PortalTTokenRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

interface EWorkspaceSlugEventSlugRouteRouteChildren {
  EWorkspaceSlugEventSlugSplatRoute: typeof EWorkspaceSlugEventSlugSplatRoute
  EWorkspaceSlugEventSlugMyScheduleRoute: typeof EWorkspaceSlugEventSlugMyScheduleRoute
  EWorkspaceSlugEventSlugSpeakersRoute: typeof EWorkspaceSlugEventSlugSpeakersRoute
  EWorkspaceSlugEventSlugIndexRoute: typeof EWorkspaceSlugEventSlugIndexRoute
  EWorkspaceSlugEventSlugItineraryPersonIdRoute: typeof EWorkspaceSlugEventSlugItineraryPersonIdRoute
  EWorkspaceSlugEventSlugSessionsSessionIdRoute: typeof EWorkspaceSlugEventSlugSessionsSessionIdRoute
  EWorkspaceSlugEventSlugSessionsIndexRoute: typeof EWorkspaceSlugEventSlugSessionsIndexRoute
}

const EWorkspaceSlugEventSlugRouteRouteChildren: EWorkspaceSlugEventSlugRouteRouteChildren =
  {
    EWorkspaceSlugEventSlugSplatRoute: EWorkspaceSlugEventSlugSplatRoute,
    EWorkspaceSlugEventSlugMyScheduleRoute:
      EWorkspaceSlugEventSlugMyScheduleRoute,
    EWorkspaceSlugEventSlugSpeakersRoute: EWorkspaceSlugEventSlugSpeakersRoute,
    EWorkspaceSlugEventSlugIndexRoute: EWorkspaceSlugEventSlugIndexRoute,
    EWorkspaceSlugEventSlugItineraryPersonIdRoute:
      EWorkspaceSlugEventSlugItineraryPersonIdRoute,
    EWorkspaceSlugEventSlugSessionsSessionIdRoute:
      EWorkspaceSlugEventSlugSessionsSessionIdRoute,
    EWorkspaceSlugEventSlugSessionsIndexRoute:
      EWorkspaceSlugEventSlugSessionsIndexRoute,
  }

const EWorkspaceSlugEventSlugRouteRouteWithChildren =
  EWorkspaceSlugEventSlugRouteRoute._addFileChildren(
    EWorkspaceSlugEventSlugRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  ConfirmEmailRoute: ConfirmEmailRoute,
  DesignSystemRoute: DesignSystemRoute,
  GetRoute: GetRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  ApiChatRoute: ApiChatRoute,
  DocsApiRoute: DocsApiRoute,
  ReviewTokenRoute: ReviewTokenRoute,
  EWorkspaceSlugEventSlugRouteRoute:
    EWorkspaceSlugEventSlugRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  EWorkspaceSlugIndexRoute: EWorkspaceSlugIndexRoute,
  SubmitWorkspaceSlugIndexRoute: SubmitWorkspaceSlugIndexRoute,
  SubmitWorkspaceSlugEventSlugFormSlugRoute:
    SubmitWorkspaceSlugEventSlugFormSlugRoute,
  SubmitWorkspaceSlugEventSlugIndexRoute:
    SubmitWorkspaceSlugEventSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
